# Generated by Django 5.0.14 on 2026-09-15 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyKillSwitch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global Shutdown of All Mobile Forwarding'), ('DESTINATION', 'Disable Specific Destination'), ('DEVICE', 'Disable Specific Mobile Device'), ('RULE', 'Disable Specific Forwarding Rule'), ('USER', 'Disable All Forwarding for User')], default='GLOBAL', max_length=20)),
                ('target_id', models.CharField(blank=True, default='', help_text='Target UUID/Identifier when scope is not GLOBAL.', max_length=128)),
                ('reason', models.TextField(help_text='Clinical / Security reason for activation.')),
                ('is_active', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_kill_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_emergency_kill_switches',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForwardingDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('destination_type', models.CharField(choices=[('SECURE_WEBHOOK', 'Secure Webhook (HTTPS/HMAC)'), ('EMAIL', 'Approved Hospital Email'), ('INTERNAL_API', 'Internal Clinical API'), ('PUSH_NOTIFICATION', 'Clinical Push Notification'), ('ENTERPRISE_CHAT', 'Enterprise Messaging'), ('SMS', 'Controlled Outbound SMS'), ('OTHER_APPROVED', 'Other Security-Approved Destination')], default='INTERNAL_API', max_length=32)),
                ('endpoint', models.CharField(help_text='Verified HTTPS URL or approved destination identifier.', max_length=500)),
                ('environment', models.CharField(default='PRODUCTION', max_length=32)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Clinical/IT Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('data_classification_allowed', models.JSONField(default=list, help_text="List of permitted classifications e.g. ['PUBLIC', 'LOW_SENSITIVITY']")),
                ('encryption_required', models.BooleanField(default=True)),
                ('webhook_signing_secret', models.CharField(blank=True, max_length=128)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('enabled', models.BooleanField(default=False, help_text='Default-deny forwarding flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_destinations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_forwarding_destinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForwardingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('SMS_RECEIVED', 'SMS Received'), ('CALL_RECEIVED', 'Call Event'), ('APP_NOTIFICATION', 'App Notification'), ('SYSTEM_EVENT', 'System Event'), ('BATTERY_EVENT', 'Battery / Power Event'), ('NETWORK_EVENT', 'Network State Event'), ('DEVICE_STATUS', 'Device Heartbeat / Status'), ('ALL', 'All Permitted Events')], default='ALL', max_length=32)),
                ('source_filter', models.CharField(default='*', help_text='Sender number pattern or application package (glob/regex).', max_length=255)),
                ('content_filter', models.CharField(blank=True, default='', help_text='Regex keyword filter (declarative only).', max_length=500)),
                ('classification_policy', models.CharField(choices=[('ALLOW', 'Allow Forwarding'), ('BLOCK', 'Block Event'), ('REDACT', 'Redact Sensitive Data & Forward'), ('REVIEW_REQUIRED', 'Require Human Clinician Review')], default='BLOCK', help_text='Policy outcome when rule criteria matches.', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Rule evaluation priority: lower integer = evaluated first.')),
                ('enabled', models.BooleanField(default=False, help_text='Default-deny rule state.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mobile_gateway.forwardingdestination')),
            ],
            options={
                'db_table': 'mobile_forwarding_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_identifier', models.CharField(db_index=True, help_text='Hardware/app-generated unique device identity hash.', max_length=128, unique=True)),
                ('device_name', models.CharField(default='Android Device', max_length=100)),
                ('platform', models.CharField(default='ANDROID', max_length=32)),
                ('app_version', models.CharField(default='3.42.0', max_length=32)),
                ('os_version', models.CharField(blank=True, default='Android 14', max_length=32)),
                ('registration_status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked'), ('LOST', 'Reported Lost'), ('DECOMMISSIONED', 'Decommissioned')], db_index=True, default='PENDING', max_length=20)),
                ('public_key', models.TextField(blank=True, help_text='Device public key stored in PEM or Hex format for HMAC/ECDSA verification.')),
                ('shared_secret', models.CharField(blank=True, help_text='Cryptographic device secret (stored securely for HMAC verification).', max_length=128)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owning patient or authorized staff user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobile_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SMS_RECEIVED', 'SMS Received'), ('CALL_RECEIVED', 'Call Event'), ('APP_NOTIFICATION', 'App Notification'), ('SYSTEM_EVENT', 'System Event'), ('BATTERY_EVENT', 'Battery / Power Event'), ('NETWORK_EVENT', 'Network State Event'), ('DEVICE_STATUS', 'Device Heartbeat / Status'), ('ALL', 'All Permitted Events')], max_length=32)),
                ('source', models.CharField(help_text='Sender phone number or application package name.', max_length=255)),
                ('timestamp', models.DateTimeField(help_text='Event timestamp reported by device.')),
                ('content', models.TextField(blank=True, help_text='Sanitized / redacted event content.')),
                ('raw_hash', models.CharField(blank=True, help_text='SHA-256 hash of original payload for tamper-evidence and deduplication.', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public Information'), ('LOW_SENSITIVITY', 'Low Sensitivity (Operational)'), ('SENSITIVE', 'Sensitive Non-Clinical'), ('PHI', 'Protected Health Information'), ('OTP', 'One-Time Password / Auth Secret'), ('AUTHENTICATION_SECRET', 'Credential / Key / Secret'), ('FINANCIAL', 'Financial / Billing Information'), ('UNKNOWN', 'Unknown / Unclassified')], db_index=True, default='UNKNOWN', max_length=32)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Security Risk')], default='LOW', max_length=20)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received by Gateway'), ('CLASSIFIED', 'Classified by Policy Engine'), ('BLOCKED', 'Blocked by Policy'), ('REDACTED', 'Sanitized / Redacted'), ('APPROVED', 'Approved for Delivery'), ('QUEUED', 'Queued in Celery'), ('SENDING', 'Transmitting to Destination'), ('DELIVERED', 'Successfully Delivered'), ('FAILED', 'Transmission Failed'), ('RETRYING', 'Retrying with Backoff'), ('DEAD_LETTER', 'Routed to Dead-Letter Queue'), ('EXPIRED', 'Expired (Retention TTL)'), ('CANCELLED', 'Cancelled by Kill Switch')], db_index=True, default='RECEIVED', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Unique key ensuring duplicate events are discarded.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mobile_gateway.mobiledevice')),
            ],
            options={
                'db_table': 'mobile_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], max_length=20)),
                ('latency_ms', models.IntegerField(default=0)),
                ('provider_response_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mobile_gateway.forwardingdestination')),
                ('mobile_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='mobile_gateway.mobileevent')),
            ],
            options={
                'db_table': 'mobile_delivery_receipts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_reason', models.TextField()),
                ('attempt_count', models.IntegerField(default=1)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('next_retry', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('DISCARDED', 'Discarded'), ('REQUEUED', 'Requeued')], default='PENDING_REVIEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letters', to='mobile_gateway.forwardingdestination')),
                ('mobile_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_letters', to='mobile_gateway.mobileevent')),
            ],
            options={
                'db_table': 'mobile_dead_letter_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
