# Generated by Django 5.0.14 on 2026-09-13 05:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of observation measurement.')),
                ('encounter_type', models.CharField(choices=[('ROUTINE', 'Routine Checkup'), ('OUTPATIENT', 'Outpatient Clinic'), ('INPATIENT', 'Inpatient Ward'), ('EMERGENCY', 'Emergency Department'), ('ICU', 'Intensive Care Unit')], db_index=True, default='OUTPATIENT', max_length=50)),
                ('systolic_bp', models.IntegerField(blank=True, help_text='Systolic blood pressure (mmHg).', null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='Diastolic blood pressure (mmHg).', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Pulse rate (beats per minute).', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breathing rate (breaths per minute).', null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Core body temperature (°C).', max_digits=4, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='Pulse oximetry SpO2 percentage (0-100%).', max_digits=4, null=True)),
                ('glucose_level', models.DecimalField(blank=True, decimal_places=1, help_text='Blood glucose level (mg/dL).', max_digits=5, null=True)),
                ('cholesterol_total', models.DecimalField(blank=True, decimal_places=1, help_text='Total cholesterol (mg/dL).', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, help_text='Body Mass Index (kg/m²).', max_digits=4, null=True)),
                ('symptoms', models.TextField(blank=True, help_text='Reported symptoms and clinical presentation.')),
                ('clinical_notes', models.TextField(blank=True, help_text='Attending physician notes and impressions.')),
                ('lab_results', models.JSONField(blank=True, default=dict, help_text='Comprehensive structured laboratory panel results.')),
                ('patient', models.ForeignKey(help_text='Patient associated with this clinical record.', on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='patients.patient')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Clinician who recorded or verified these vitals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_clinical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Record',
                'verbose_name_plural': 'Clinical Records',
                'db_table': 'clinical_records',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'recorded_at'], name='clinical_re_patient_c2dab5_idx'), models.Index(fields=['recorded_at'], name='clinical_re_recorde_2e9e41_idx'), models.Index(fields=['encounter_type', 'recorded_at'], name='clinical_re_encount_d3cbe4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('systolic_bp__isnull', True), ('systolic_bp__gt', 0), _connector='OR'), name='check_systolic_bp_positive'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('diastolic_bp__isnull', True), ('diastolic_bp__gt', 0), _connector='OR'), name='check_diastolic_bp_positive'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('heart_rate__isnull', True), ('heart_rate__gt', 0), _connector='OR'), name='check_heart_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('oxygen_saturation__isnull', True), models.Q(('oxygen_saturation__gte', 0), ('oxygen_saturation__lte', 100)), _connector='OR'), name='check_oxygen_saturation_range'),
        ),
    ]
