# Generated by Django 5.0.14 on 2026-09-13 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalrecord',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Serum calcium concentration (mg/dL).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='creatinine',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum creatinine level (mg/dL).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='lactic_acid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Serum lactic acid / lactate concentration (mmol/L).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='clinicalrecord',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Serum sodium concentration (mmol/L or mEq/L).', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='clinicalrecord',
            index=models.Index(fields=['recorded_by', 'recorded_at'], name='clinical_re_recorde_af3f45_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('creatinine__isnull', True), ('creatinine__gte', 0), _connector='OR'), name='check_creatinine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('sodium__isnull', True), ('sodium__gte', 0), _connector='OR'), name='check_sodium_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('calcium__isnull', True), ('calcium__gte', 0), _connector='OR'), name='check_calcium_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clinicalrecord',
            constraint=models.CheckConstraint(check=models.Q(('lactic_acid__isnull', True), ('lactic_acid__gte', 0), _connector='OR'), name='check_lactic_acid_non_negative'),
        ),
    ]
