# Generated by Django 5.0.14 on 2026-09-13 17:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_clinicalrecord_calcium_clinicalrecord_creatinine_and_more'),
        ('patients', '0002_patient_user'),
        ('predictions', '0002_clinicalreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('VITALS_CHECK', 'Vital Signs Check'), ('MEDICATION_ADMIN', 'Medication Administration'), ('TRIAGE_REASSESS', 'Triage Reassessment'), ('LAB_DRAW', 'Stat Laboratory Draw'), ('DISCHARGE_PREP', 'Discharge Preparation')], default='VITALS_CHECK', max_length=30)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Emergency / STAT')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_tasks', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Clinical Task',
                'verbose_name_plural': 'Clinical Tasks',
                'db_table': 'clinical_tasks',
                'ordering': ['due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('reason', models.TextField(help_text='Clinical justification for urgent escalation.')),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('CRITICAL', 'Critical / STAT Alert')], db_index=True, default='HIGH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACKNOWLEDGED', 'Acknowledged by Doctor'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=20)),
                ('doctor_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_escalations', to=settings.AUTH_USER_MODEL)),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_escalations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='patients.patient')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='predictions.prediction')),
            ],
            options={
                'verbose_name': 'Clinical Escalation',
                'verbose_name_plural': 'Clinical Escalations',
                'db_table': 'clinical_escalations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting for Triage'), ('TRIAGE_IN_PROGRESS', 'Triage in Progress'), ('TRIAGED', 'Triaged / Bed Assigned'), ('ESCALATED', 'Escalated to Physician'), ('COMPLETED', 'Triage Completed')], db_index=True, default='WAITING', max_length=30)),
                ('acuity_level', models.IntegerField(default=3, help_text='Emergency Severity Index: 1 (Resuscitation) to 5 (Non-urgent).')),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('bed_assignment', models.CharField(blank=True, max_length=50)),
                ('arrival_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reassessment_due', models.DateTimeField(blank=True, null=True)),
                ('triage_notes', models.TextField(blank=True)),
                ('nurse', models.ForeignKey(blank=True, help_text='Triage nurse managing patient intake.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_triage_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient undergoing triage.', on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Triage Record',
                'verbose_name_plural': 'Triage Records',
                'db_table': 'triage_records',
                'ordering': ['acuity_level', 'arrival_time'],
            },
        ),
    ]
