# Generated by Django 5.0.14 on 2026-09-18 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_clinicaltask_escalation_triagerecord'),
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('issue_type', models.CharField(choices=[('INVALID_VALUE', 'Physiologically Invalid Value'), ('OUTLIER', 'Statistical Outlier'), ('MISSING_CRITICAL', 'Missing Critical Clinical Feature'), ('UNIT_MISMATCH', 'Inconsistent Units'), ('DUPLICATE', 'Duplicate Encounter Record'), ('SCHEMA_MISMATCH', 'Schema Mismatch'), ('DISTRIBUTION_DRIFT', 'Distribution Drift')], db_index=True, default='INVALID_VALUE', max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('feature_name', models.CharField(db_index=True, max_length=100)),
                ('observed_value', models.TextField(blank=True)),
                ('expected_range', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='ClinicalRecord', max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='OPEN', max_length=30)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Clinician or informaticist assigned to audit/remediate the issue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_data_issues', to=settings.AUTH_USER_MODEL)),
                ('clinical_record', models.ForeignKey(blank=True, help_text='Clinical record containing anomalous measurement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_quality_issues', to='clinical.clinicalrecord')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient record linked to this data anomaly.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_issues', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Clinical Data Quality Issue',
                'verbose_name_plural': 'Clinical Data Quality Issues',
                'db_table': 'clinical_data_quality_issues',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='clinical_da_status_a51f3a_idx'), models.Index(fields=['patient', 'status'], name='clinical_da_patient_bba948_idx')],
            },
        ),
    ]
