# Generated by Django 5.0.14 on 2026-09-18 06:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_dataqualityissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalFeatureDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('data_type', models.CharField(choices=[('NUMERICAL', 'Numerical / Continuous'), ('CATEGORICAL', 'Categorical / Discrete'), ('BOOLEAN', 'Boolean Flag')], default='NUMERICAL', max_length=30)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('preprocessing_strategy', models.CharField(choices=[('STANDARD_SCALER', 'Standard Scaler + Median Impute'), ('ROBUST_SCALER', 'Robust Scaler + Median Impute'), ('ONE_HOT', 'One-Hot Encoding'), ('PASS_THROUGH', 'Pass Through')], default='STANDARD_SCALER', max_length=50)),
                ('clinical_category', models.CharField(choices=[('DEMOGRAPHIC', 'Demographic'), ('CARDIOVASCULAR', 'Cardiovascular'), ('RESPIRATORY', 'Respiratory'), ('VITAL', 'Vital Signs'), ('METABOLIC', 'Metabolic'), ('ELECTROLYTE', 'Electrolytes'), ('RENAL', 'Renal Function'), ('ENCOUNTER', 'Encounter Details')], default='VITAL', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
            ],
            options={
                'verbose_name': 'Clinical Feature Definition',
                'verbose_name_plural': 'Clinical Feature Definitions',
                'db_table': 'clinical_feature_definitions',
                'ordering': ['clinical_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('rule_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('condition_expression', models.JSONField(default=dict, help_text='Structured rule predicates.')),
                ('severity', models.CharField(choices=[('ROUTINE', 'Routine Observation'), ('MONITOR', 'Increased Monitoring'), ('URGENT', 'Urgent Clinical Review'), ('CRITICAL', 'Critical Emergency / STAT Alert')], default='URGENT', max_length=30)),
                ('action_type', models.CharField(choices=[('BEDSIDE_EVALUATION', 'Immediate Bedside Evaluation'), ('ICU_TRANSFER', 'ICU / Specialist Consult'), ('REASSESS_1H', 'Serial Reassessment in 1 Hour'), ('SEPSIS_BUNDLE', 'Initiate Sepsis Resuscitation Bundle'), ('NOTIFY_DOCTOR', 'Notify Attending Physician')], default='BEDSIDE_EVALUATION', max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(default='APPROVED', max_length=30)),
            ],
            options={
                'verbose_name': 'Clinical Rule',
                'verbose_name_plural': 'Clinical Rules',
                'db_table': 'clinical_rules',
                'ordering': ['-severity', 'rule_name'],
            },
        ),
    ]
