# Generated by Django 5.0.14 on 2026-09-21 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_evidencereference_evidencesource_and_more'),
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttimelineevent',
            name='authorization_scope',
            field=models.CharField(choices=[('PUBLIC_PATIENT', 'Public / Patient Portal Visible'), ('CLINICAL_STAFF', 'Clinical Staff (Doctor / Nurse)'), ('INFORMATICIST_ADMIN', 'Medical Informaticist & Admin Only')], db_index=True, default='CLINICAL_STAFF', max_length=32),
        ),
        migrations.AddField(
            model_name='patienttimelineevent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Validated'), ('SUPERSEDED', 'Superseded'), ('DISMISSED', 'Dismissed'), ('REQUIRES_REVIEW', 'Requires Review')], db_index=True, default='ACTIVE', max_length=32),
        ),
        migrations.AlterField(
            model_name='patienttimelineevent',
            name='event_type',
            field=models.CharField(choices=[('ENCOUNTER', 'Clinical Encounter'), ('OBSERVATION', 'Clinical Observation'), ('VITAL', 'Vital Signs Measurement'), ('CONDITION', 'Medical Condition / Diagnosis'), ('DIAGNOSTIC_REPORT', 'Diagnostic Lab / Imaging Report'), ('MEDICATION', 'Medication Administration / Order'), ('FHIR_IMPORT', 'FHIR Interoperability Import'), ('FHIR_UPDATE', 'FHIR Resource Update'), ('RISK_PREDICTION', 'ML Risk Level Prediction'), ('PREDICTION_REVIEW', 'Clinician Prediction Review'), ('PREDICTION_OVERRIDE', 'Clinician Prediction Override'), ('CLINICAL_ALERT', 'Clinical Safety Alert'), ('ESCALATION', 'Clinical Deterioration Escalation'), ('DATA_QUALITY_EVENT', 'Clinical Data Quality Event'), ('CONSENT_EVENT', 'Patient Consent Event'), ('CLINICAL_NOTE', 'Clinician Progress / Consultation Note'), ('MODEL_EVENT', 'ML Model Lifecycle / Drift Event'), ('PATIENT_ADMISSION', 'Patient Admission'), ('VITAL_OBSERVATION', 'Vital Signs Observation'), ('LAB_RESULT', 'Laboratory Result'), ('CLINICAL_REVIEW', 'Physician Clinical Review'), ('NURSE_TRIAGE', 'Nursing Triage & Acuity'), ('GUIDELINE_APPLIED', 'Guideline Applied'), ('AI_INTERACTION', 'AI Decision Support Interaction'), ('AUDIT_EVENT', 'Clinical Audit Event')], db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='patienttimelineevent',
            index=models.Index(fields=['authorization_scope', 'status'], name='patient_tim_authori_07bf08_idx'),
        ),
    ]
