# Generated by Django 5.0.14 on 2026-09-17 10:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NocoDBConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Primary NocoDB Analytics Engine', max_length=100)),
                ('base_url', models.CharField(default='http://nocodb:8080', help_text='Internal HTTP endpoint for NocoDB container', max_length=255)),
                ('api_token', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='HEALTHY', max_length=50)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NocoDB Connection',
                'verbose_name_plural': 'NocoDB Connections',
            },
        ),
        migrations.CreateModel(
            name='NocoDBDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('ML_OPS', 'ML & AI Operations'), ('DATA_QUALITY', 'Data Quality & Integrity'), ('CLINICAL_OPS', 'Clinical Workflow Operations'), ('SYSTEM_TELEMETRY', 'System & API Telemetry'), ('COLLABORATION', 'Collaboration & Whiteboards'), ('GENERAL', 'General Analytics')], default='GENERAL', max_length=50)),
                ('allowed_roles', models.JSONField(default=list, help_text="List of roles permitted to access this dataset (e.g. ['informaticist', 'admin', 'doctor'])")),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_dataset', models.BooleanField(default=True, help_text='System-managed projection synchronized from Neon PostgreSQL')),
                ('source_model', models.CharField(blank=True, default='', help_text="Underlying Django model string, e.g. 'predictions.Prediction'", max_length=100)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NocoDB Governed Dataset',
                'verbose_name_plural': 'NocoDB Governed Datasets',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NocoDBWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('signature', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NocoDB Webhook Event',
                'verbose_name_plural': 'NocoDB Webhook Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NocoDBAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(blank=True, default='system', max_length=50)),
                ('action', models.CharField(choices=[('VIEW', 'View Dataset'), ('FILTER', 'Filter Query'), ('INSERT', 'Insert Row'), ('UPDATE', 'Update Row'), ('DELETE', 'Delete Row'), ('EXPORT', 'Export Dataset'), ('SYNC', 'Sync Projection'), ('MCP_TOOL_INVOCATION', 'MCP Tool Invocation'), ('SCHEMA_CHANGE', 'Schema Change')], db_index=True, max_length=50)),
                ('dataset_slug', models.CharField(db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nocodb_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NocoDB Audit Event',
                'verbose_name_plural': 'NocoDB Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NocoDBViewPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('view_type', models.CharField(choices=[('grid', 'Grid View'), ('gallery', 'Gallery View'), ('kanban', 'Kanban View'), ('form', 'Form View')], default='grid', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Saved layout: {filters: [], sorts: [], hidden_columns: []}')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='nocodb.nocodbdataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nocodb_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NocoDB View Preference',
                'verbose_name_plural': 'NocoDB View Preferences',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NocoDBRowRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anon_ref_id', models.CharField(db_index=True, help_text='Deterministic pseudonymous reference hash', max_length=128)),
                ('data', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='nocodb.nocodbdataset')),
            ],
            options={
                'verbose_name': 'NocoDB Row Record',
                'verbose_name_plural': 'NocoDB Row Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'anon_ref_id'], name='nocodb_noco_dataset_22ac5a_idx'), models.Index(fields=['dataset', 'is_archived', '-created_at'], name='nocodb_noco_dataset_50d930_idx')],
            },
        ),
        migrations.CreateModel(
            name='NocoDBSchemaColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('display_name', models.CharField(max_length=150)),
                ('column_type', models.CharField(choices=[('SingleLineText', 'Single Line Text'), ('Number', 'Number'), ('Rating', 'Rating'), ('Select', 'Single Select'), ('MultiSelect', 'Multi Select'), ('Formula', 'Formula'), ('Checkbox', 'Checkbox'), ('DateTime', 'Date & Time'), ('Date', 'Date'), ('JSON', 'JSON Object')], default='SingleLineText', max_length=50)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_phi', models.BooleanField(default=False, help_text='Flag indicating column contains sensitive PHI, requiring strict masking')),
                ('is_read_only', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list, help_text='Allowed options for Select/MultiSelect column types')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='nocodb.nocodbdataset')),
            ],
            options={
                'verbose_name': 'NocoDB Schema Column',
                'verbose_name_plural': 'NocoDB Schema Columns',
                'ordering': ['order', 'name'],
                'unique_together': {('dataset', 'name')},
            },
        ),
    ]
