# Generated by Django 5.0.14 on 2026-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='system_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
