# Generated by Django 5.0.14 on 2026-09-23 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0002_agentdefinition_system_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('purpose', models.TextField(help_text='Clinical or operational justification for this domain.')),
                ('environment', models.CharField(default='PRODUCTION', max_length=50)),
                ('owner', models.CharField(default='Security Administration', max_length=150)),
                ('allowed_operations', models.JSONField(default=list, help_text='Allowed browser operations (e.g. READ_PUBLIC, NAVIGATE)')),
                ('phi_allowed', models.BooleanField(default=False, help_text='Whether PHI transmission is permitted. Default DENY.')),
                ('authentication_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Approved Destination',
                'verbose_name_plural': 'Approved Destinations',
                'db_table': 'approved_destinations',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='AgentKillSwitchState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_active', models.BooleanField(default=False, help_text='True if emergency kill switch is activated.')),
                ('reason', models.TextField(blank=True, default='')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_kill_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Kill Switch State',
                'verbose_name_plural': 'Agent Kill Switch States',
                'db_table': 'agent_kill_switch_state',
            },
        ),
        migrations.CreateModel(
            name='BrowserAgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('role', models.CharField(default='ADMIN', max_length=50)),
                ('goal', models.TextField(help_text='Natural-language goal for controlled browser execution.')),
                ('destination_url', models.URLField(max_length=1000)),
                ('destination_domain', models.CharField(db_index=True, max_length=255)),
                ('environment', models.CharField(default='PRODUCTION', max_length=50)),
                ('risk_level', models.CharField(choices=[('READ_ONLY', 'Read Only'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Clinical Action')], db_index=True, default='LOW', max_length=30)),
                ('phi_classification', models.CharField(choices=[('PUBLIC', 'Public / General Medical'), ('LOW_SENSITIVITY', 'Low Sensitivity'), ('SENSITIVE', 'Sensitive Operational'), ('PHI', 'Protected Health Information'), ('HIGHLY_SENSITIVE', 'Highly Sensitive Psychiatric/Genetic'), ('AUTHENTICATION_SECRET', 'Authentication Secret / Credentials')], db_index=True, default='PUBLIC', max_length=50)),
                ('approval_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('APPROVED', 'Approved'), ('RUNNING', 'Running'), ('VERIFYING', 'Verifying'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out'), ('REQUIRES_HUMAN_ACTION', 'Requires Human Action')], db_index=True, default='PENDING', max_length=35)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], db_index=True, default='UNVERIFIED', max_length=30)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('audit_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('independent_verification_rules', models.JSONField(blank=True, default=dict, help_text='Programmatic rules to independently verify the outcome (e.g., expected text, selector present).')),
                ('steps_log', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_browser_tasks', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Browser Agent Task',
                'verbose_name_plural': 'Browser Agent Tasks',
                'db_table': 'browser_agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
