# Generated by Django 5.0.14 on 2026-09-25 07:14

import apps.ai_agents.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0003_approveddestination_agentkillswitchstate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserAgentAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('step_index', models.IntegerField(default=1)),
                ('operation', models.CharField(max_length=50)),
                ('target_index', models.CharField(blank=True, default='', max_length=50)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('target_role', models.CharField(blank=True, default='', max_length=50)),
                ('input_text', models.CharField(blank=True, default='', max_length=500)),
                ('is_mutation', models.BooleanField(default=False)),
                ('elapsed_ms', models.IntegerField(default=0)),
                ('page_changed', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(default='COMPLETED', max_length=50)),
            ],
            options={
                'db_table': 'browser_agent_actions',
                'ordering': ['step_index'],
            },
        ),
        migrations.CreateModel(
            name='BrowserAgentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('destination', models.CharField(blank=True, default='', max_length=255)),
                ('security_decision', models.CharField(default='ALLOW', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'browser_agent_audit_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BrowserAgentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('provider_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='0.1.0', max_length=30)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('runtime_mode', models.CharField(default='sandbox', max_length=30)),
                ('max_concurrent_sessions', models.IntegerField(default=5)),
                ('config_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Browser Agent Provider',
                'verbose_name_plural': 'Browser Agent Providers',
                'db_table': 'browser_agent_providers',
            },
        ),
        migrations.CreateModel(
            name='BrowserAgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('steps_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('VERIFICATION_FAILED', 'Verification Failed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('VERIFYING', 'Verifying'), ('SUCCEEDED', 'Succeeded'), ('TIMED_OUT', 'Timed Out'), ('REQUIRES_HUMAN_ACTION', 'Requires Human Action')], default='RUNNING', max_length=35)),
                ('provider_latency_ms', models.IntegerField(default=0)),
                ('text_helper_latency_ms', models.IntegerField(default=0)),
                ('model_calls_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'browser_agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrowserApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('decision', models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='APPROVED', max_length=30)),
                ('justification', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browser_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'browser_approvals',
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='BrowserArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(max_length=50)),
                ('phi_classification', models.CharField(choices=[('PUBLIC', 'Public / General Medical'), ('LOW_SENSITIVITY', 'Low Sensitivity'), ('SENSITIVE', 'Sensitive Operational'), ('PHI', 'Protected Health Information'), ('HIGHLY_SENSITIVE', 'Highly Sensitive Psychiatric/Genetic'), ('AUTHENTICATION_SECRET', 'Authentication Secret / Credentials')], default='PUBLIC', max_length=50)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(default='application/json', max_length=100)),
                ('size_bytes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'browser_artifacts',
            },
        ),
        migrations.CreateModel(
            name='BrowserDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('hostname', models.CharField(blank=True, db_index=True, max_length=255)),
                ('scheme', models.CharField(default='https', max_length=10)),
                ('port', models.IntegerField(default=443)),
                ('allowed_paths', models.JSONField(blank=True, default=list, help_text="Allowed URL path prefixes, e.g. ['/docs', '/guidelines'].")),
                ('allowed_operations', models.JSONField(blank=True, default=list, help_text="Allowed operations, e.g. ['CLICK', 'TYPE_TEXT', 'WAIT', 'DONE'].")),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text="Allowed roles e.g. ['ADMIN', 'INFORMATICIST', 'DOCTOR'].")),
                ('sensitivity', models.CharField(choices=[('PUBLIC', 'Public / General Medical'), ('LOW_SENSITIVITY', 'Low Sensitivity'), ('SENSITIVE', 'Sensitive Operational'), ('PHI', 'Protected Health Information'), ('HIGHLY_SENSITIVE', 'Highly Sensitive Psychiatric/Genetic'), ('AUTHENTICATION_SECRET', 'Authentication Secret / Credentials')], default='PUBLIC', max_length=50)),
                ('approval_required', models.BooleanField(default=False)),
                ('purpose', models.TextField(help_text='Clinical or operational justification for this domain.')),
                ('environment', models.CharField(default='PRODUCTION', max_length=50)),
                ('owner', models.CharField(default='Security Administration', max_length=150)),
                ('phi_allowed', models.BooleanField(default=False, help_text='Whether PHI transmission is permitted. Default DENY.')),
                ('authentication_required', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Approved Destination',
                'verbose_name_plural': 'Approved Destinations',
                'db_table': 'approved_destinations',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='BrowserTaskPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('task_type', models.CharField(db_index=True, default='GENERAL_BROWSER_READ', max_length=100)),
                ('destination', models.CharField(default='*', help_text='Hostname or wildcard pattern', max_length=255)),
                ('allowed_operations', models.JSONField(default=apps.ai_agents.models.default_allowed_operations, help_text='Permitted browser operations.')),
                ('sensitivity', models.CharField(choices=[('PUBLIC', 'Public / General Medical'), ('LOW_SENSITIVITY', 'Low Sensitivity'), ('SENSITIVE', 'Sensitive Operational'), ('PHI', 'Protected Health Information'), ('HIGHLY_SENSITIVE', 'Highly Sensitive Psychiatric/Genetic'), ('AUTHENTICATION_SECRET', 'Authentication Secret / Credentials')], default='PUBLIC', max_length=50)),
                ('required_role', models.CharField(choices=[('DOCTOR', 'Physician / Doctor'), ('NURSE', 'Nurse / Triage'), ('PATIENT', 'Patient / User'), ('INFORMATICIST', 'Medical Informaticist'), ('ADMIN', 'System Administrator'), ('GENERAL', 'General Clinical')], default='DOCTOR', max_length=50)),
                ('approval_required', models.BooleanField(default=False)),
                ('max_steps', models.IntegerField(default=15)),
                ('max_duration', models.IntegerField(default=60, help_text='Maximum execution duration in seconds')),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Browser Task Policy',
                'verbose_name_plural': 'Browser Task Policies',
                'db_table': 'browser_task_policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrowserVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='UNVERIFIED', max_length=30)),
                ('rules_applied', models.JSONField(blank=True, default=dict)),
                ('checks_passed', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'browser_verifications',
            },
        ),
        migrations.DeleteModel(
            name='ApprovedDestination',
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='allowed_operations',
            field=models.JSONField(blank=True, default=apps.ai_agents.models.default_allowed_operations),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='artifacts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='browser_session_reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='patient_context_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='provider',
            field=models.CharField(db_index=True, default='jev-ultrafast', max_length=50),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='provider_version',
            field=models.CharField(default='0.1.0', max_length=30),
        ),
        migrations.AddField(
            model_name='browseragenttask',
            name='sensitivity_classification',
            field=models.CharField(choices=[('PUBLIC', 'Public / General Medical'), ('LOW_SENSITIVITY', 'Low Sensitivity'), ('SENSITIVE', 'Sensitive Operational'), ('PHI', 'Protected Health Information'), ('HIGHLY_SENSITIVE', 'Highly Sensitive Psychiatric/Genetic'), ('AUTHENTICATION_SECRET', 'Authentication Secret / Credentials')], db_index=True, default='PUBLIC', max_length=50),
        ),
        migrations.AlterField(
            model_name='browseragenttask',
            name='execution_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATING', 'Validating'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('VERIFICATION_FAILED', 'Verification Failed'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('VERIFYING', 'Verifying'), ('SUCCEEDED', 'Succeeded'), ('TIMED_OUT', 'Timed Out'), ('REQUIRES_HUMAN_ACTION', 'Requires Human Action')], db_index=True, default='READY', max_length=35),
        ),
        migrations.AddField(
            model_name='browseragentaction',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai_agents.browseragenttask'),
        ),
        migrations.AddField(
            model_name='browseragentauditevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='ai_agents.browseragenttask'),
        ),
        migrations.AddField(
            model_name='browseragentrun',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_agents.browseragenttask'),
        ),
        migrations.AddField(
            model_name='browseragentaction',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='ai_agents.browseragentrun'),
        ),
        migrations.AddField(
            model_name='browserapproval',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ai_agents.browseragenttask'),
        ),
        migrations.AddField(
            model_name='browserartifact',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_files', to='ai_agents.browseragenttask'),
        ),
        migrations.AddField(
            model_name='browserverification',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_record', to='ai_agents.browseragenttask'),
        ),
    ]
