# Generated by Django 5.0.14 on 2026-09-13 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('model_name', models.CharField(db_index=True, help_text="Clinical target identifier (e.g. 'maternal_mortality_ensemble').", max_length=100)),
                ('algorithm', models.CharField(help_text="Algorithm family (e.g. 'RandomForestClassifier', 'AdaBoost', 'SVM').", max_length=100)),
                ('version', models.CharField(db_index=True, help_text="Semantic version string (e.g. '1.0.0').", max_length=50)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('STAGING', 'Staging'), ('ACTIVE', 'Active (Production)'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], db_index=True, default='CANDIDATE', help_text='Deployment lifecycle status.', max_length=30)),
                ('artifact_location', models.CharField(help_text='Persistent storage URI or filesystem artifact path.', max_length=500)),
                ('feature_schema_version', models.CharField(default='v1.0', help_text='Expected input feature schema version.', max_length=50)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Validation metrics: accuracy, roc_auc, f1, precision, recall, brier_score.')),
                ('hyperparameters', models.JSONField(blank=True, default=dict, help_text='Model hyperparameter configuration.')),
                ('training_dataset_info', models.JSONField(blank=True, default=dict, help_text='Dataset metadata: name, sample_count, feature_count, balance_ratio.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered or registered this model build.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Version',
                'verbose_name_plural': 'Model Versions',
                'db_table': 'model_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'version'], name='model_versi_model_n_f1e0b7_idx'), models.Index(fields=['status', 'created_at'], name='model_versi_status_d6400d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('model_name', 'version'), name='unique_model_name_version'),
        ),
    ]
