# Generated by Django 5.0.14 on 2026-09-13 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Overall accuracy on test partition (0.0000 - 1.0000).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this version was promoted to production.', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='activated_by',
            field=models.ForeignKey(blank=True, help_text='Clinician or administrator who approved production deployment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='f1_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Macro-averaged F1 score (0.0000 - 1.0000).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='precision',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Macro-averaged precision metric (0.0000 - 1.0000).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='preprocessing_version',
            field=models.CharField(default='v1.0', help_text='Preprocessing pipeline version applied to inputs.', max_length=50),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='recall',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Macro-averaged recall metric (0.0000 - 1.0000).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this version was retired/archived.', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='roc_auc',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Area under ROC curve where mathematically applicable.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='training_dataset_identifier',
            field=models.CharField(db_index=True, default='clinical_risk_v1', help_text='Unique identifier of the dataset used for training.', max_length=150),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Validation metrics: accuracy, roc_auc, f1, precision, recall, confusion_matrix.'),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='model_name',
            field=models.CharField(db_index=True, help_text="Clinical target identifier (e.g. 'random_forest_risk_model').", max_length=100),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='status',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('ACTIVE', 'Active (Production)'), ('ARCHIVED', 'Archived'), ('STAGING', 'Staging'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], db_index=True, default='CANDIDATE', help_text='Deployment lifecycle status.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='modelversion',
            index=models.Index(fields=['model_name', 'status'], name='model_versi_model_n_9ffc3c_idx'),
        ),
    ]
