# Generated by Django 5.0.14 on 2026-09-15 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0002_modelversion_accuracy_modelversion_activated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('dataset_identifier', models.CharField(default='clinical_risk_v1', max_length=150)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('integrity_score', models.DecimalField(decimal_places=2, default=99.0, max_digits=5)),
                ('missingness_summary', models.JSONField(default=dict)),
                ('passed_quality_gate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'data_quality_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modelversion',
            name='checksum',
            field=models.CharField(blank=True, default='', help_text='Cryptographic SHA-256 artifact hash for integrity verification.', max_length=64),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TRAINING', 'Training'), ('EVALUATING', 'Evaluating'), ('VALIDATION_FAILED', 'Validation Failed'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('STAGED', 'Staged'), ('CANARY', 'Canary'), ('PRODUCTION', 'Production'), ('DEPRECATED', 'Deprecated'), ('ROLLED_BACK', 'Rolled Back'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived'), ('ACTIVE', 'Active (Production)'), ('CANDIDATE', 'Candidate'), ('STAGING', 'Staging'), ('RETIRED', 'Retired'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', help_text='Deployment lifecycle status.', max_length=30),
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('dataset_identifier', models.CharField(db_index=True, max_length=150, unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('source', models.CharField(default='Inpatient EHR Cohort', max_length=200)),
                ('sha256_hash', models.CharField(help_text='SHA-256 fingerprint of dataset contents.', max_length=64)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('feature_count', models.PositiveIntegerField(default=14)),
                ('approval_status', models.CharField(default='APPROVED', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dataset_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('role', models.CharField(default='Medical Informaticist', max_length=50)),
                ('status', models.CharField(default='APPROVED', max_length=30)),
                ('clinical_rationale', models.TextField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='model_registry.modelversion')),
            ],
            options={
                'db_table': 'model_approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('stage', models.CharField(default='PRODUCTION', max_length=30)),
                ('traffic_percentage', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('deployed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='model_registry.modelversion')),
            ],
            options={
                'db_table': 'model_deployments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('metrics', models.JSONField(default=dict)),
                ('fairness_metrics', models.JSONField(default=dict)),
                ('brier_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('passed_safety_gates', models.BooleanField(default=True)),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model_registry.datasetversion')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='model_registry.modelversion')),
            ],
            options={
                'db_table': 'model_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelRollback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('reason', models.TextField()),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks_from', to='model_registry.modelversion')),
                ('target_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollbacks_to', to='model_registry.modelversion')),
            ],
            options={
                'db_table': 'model_rollbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
