# Generated by Django 5.0.14 on 2026-09-18 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_registry', '0003_dataqualityreport_modelversion_checksum_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('evaluation_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal (No Drift)'), ('WARNING', 'Warning (Moderate Distribution Shift)'), ('CRITICAL', 'Critical (Significant Drift Detected)')], db_index=True, default='NORMAL', max_length=20)),
                ('feature_drift_scores', models.JSONField(default=dict, help_text='Feature-level PSI and KS-test statistics.')),
                ('prediction_drift_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('features_drifted', models.JSONField(default=list, help_text='List of feature names that exceeded drift thresholds.')),
                ('summary', models.TextField(blank=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_drift_reports', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_reports', to='model_registry.modelversion')),
            ],
            options={
                'db_table': 'model_drift_reports',
                'ordering': ['-evaluation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FairnessEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('subgroup_field', models.CharField(db_index=True, default='gender', max_length=50)),
                ('subgroup_metrics', models.JSONField(default=dict, help_text='Per-subgroup accuracy, sensitivity, specificity, FPR, FNR, sample_size.')),
                ('disparate_impact_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('sample_size_warnings', models.JSONField(default=list)),
                ('evaluated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_fairness_evaluations', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_evaluations', to='model_registry.modelversion')),
            ],
            options={
                'db_table': 'model_fairness_evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
