# Generated by Django 5.0.14 on 2026-09-17 16:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(default='Medical Literature', max_length=128)),
                ('trust_tier', models.CharField(choices=[('TIER_1', 'Tier 1: Government & Regulatory Health Authority'), ('TIER_2', 'Tier 2: Academic & Peer-Reviewed Institution'), ('TIER_3', 'Tier 3: Reputable Health Media'), ('TIER_4', 'Tier 4: General Web / Unverified'), ('TIER_5', 'Tier 5: Blocked / Untrusted')], db_index=True, default='TIER_4', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired')], db_index=True, default='APPROVED', max_length=16)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of roles permitted to query this domain.')),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_domain_policies',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='WebDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('canonical_url', models.URLField(db_index=True, max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('markdown_content', models.TextField(blank=True, default='')),
                ('sanitized_html', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of markdown content.', max_length=64)),
                ('status_code', models.IntegerField(default=200)),
                ('trust_tier', models.CharField(choices=[('TIER_1', 'Tier 1: Government & Regulatory Health Authority'), ('TIER_2', 'Tier 2: Academic & Peer-Reviewed Institution'), ('TIER_3', 'Tier 3: Reputable Health Media'), ('TIER_4', 'Tier 4: General Web / Unverified'), ('TIER_5', 'Tier 5: Blocked / Untrusted')], default='TIER_4', max_length=16)),
                ('sensitivity_tier', models.CharField(default='PUBLIC', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retrieved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_documents',
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('base_url', models.URLField(max_length=1024)),
                ('trust_tier', models.CharField(choices=[('TIER_1', 'Tier 1: Government & Regulatory Health Authority'), ('TIER_2', 'Tier 2: Academic & Peer-Reviewed Institution'), ('TIER_3', 'Tier 3: Reputable Health Media'), ('TIER_4', 'Tier 4: General Web / Unverified'), ('TIER_5', 'Tier 5: Blocked / Untrusted')], default='TIER_4', max_length=16)),
                ('freshness_ttl_hours', models.IntegerField(default=168, help_text='TTL in hours before source is flagged stale.')),
                ('last_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'web_sources',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WebContentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='ANONYMOUS', max_length=64)),
                ('operation', models.CharField(db_index=True, max_length=64)),
                ('target_url', models.CharField(blank=True, default='', max_length=2048)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('decision', models.CharField(default='ALLOWED', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_content_audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebCrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upstream_job_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('role', models.CharField(default='DOCTOR', max_length=64)),
                ('base_url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], db_index=True, default='QUEUED', max_length=32)),
                ('total_pages', models.IntegerField(default=0)),
                ('completed_pages', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_crawl_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebCrawlPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('status_code', models.IntegerField(default=200)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='web_intelligence.webcrawljob')),
            ],
            options={
                'db_table': 'web_crawl_pages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebContentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('content_hash', models.CharField(max_length=64)),
                ('markdown_content', models.TextField()),
                ('diff_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='web_intelligence.webdocument')),
            ],
            options={
                'db_table': 'web_content_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='WebExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='DOCTOR', max_length=64)),
                ('target_urls', models.JSONField(default=list)),
                ('schema_definition', models.JSONField(default=dict)),
                ('extracted_data', models.JSONField(default=dict)),
                ('validation_status', models.CharField(default='VALIDATED', max_length=32)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_extractions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='DOCTOR', max_length=64)),
                ('query', models.TextField()),
                ('mode', models.CharField(choices=[('GENERAL_RESEARCH', 'General Research'), ('MEDICAL_EVIDENCE', 'Medical Evidence Mode'), ('TECHNICAL_RESEARCH', 'Technical Research'), ('ML_RESEARCH', 'Machine Learning Research'), ('SECURITY_RESEARCH', 'Security Research'), ('ADMIN_RESEARCH', 'Admin Research')], db_index=True, default='MEDICAL_EVIDENCE', max_length=32)),
                ('status', models.CharField(default='COMPLETED', max_length=32)),
                ('findings', models.TextField(blank=True, default='')),
                ('uncertainty_notes', models.TextField(blank=True, default='')),
                ('limitations', models.TextField(blank=True, default='')),
                ('conflicting_evidence', models.TextField(blank=True, default='')),
                ('clinician_review_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted by Clinician'), ('REJECTED', 'Rejected by Clinician'), ('REQUIRES_ADDITIONAL_EVIDENCE', 'Requires Additional Evidence')], db_index=True, default='UNREVIEWED', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('policy_version', models.CharField(default='1.0.0', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_research_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_research_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebResearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('evidence_quality', models.CharField(default='MODERATE', max_length=64)),
                ('conflict_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='web_intelligence.webresearchsession')),
            ],
            options={
                'db_table': 'web_research_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebResearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_number', models.IntegerField(default=1)),
                ('source_title', models.CharField(max_length=512)),
                ('source_url', models.URLField(max_length=2048)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_intelligence.webdocument')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='web_intelligence.webresearchsession')),
            ],
            options={
                'db_table': 'web_research_sources',
                'ordering': ['citation_number'],
            },
        ),
        migrations.CreateModel(
            name='WebRetrieval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='DOCTOR', max_length=64)),
                ('query', models.CharField(blank=True, default='', max_length=1024)),
                ('method', models.CharField(default='SEARCH', max_length=32)),
                ('target_url', models.URLField(blank=True, default='', max_length=2048)),
                ('result_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=32)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_retrievals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='webdocument',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='web_intelligence.websource'),
        ),
        migrations.AddIndex(
            model_name='webdocument',
            index=models.Index(fields=['content_hash', 'canonical_url'], name='web_documen_content_6aa77b_idx'),
        ),
        migrations.AddIndex(
            model_name='webdocument',
            index=models.Index(fields=['trust_tier', 'retrieved_at'], name='web_documen_trust_t_7b53c6_idx'),
        ),
    ]
