services:
  - type: web
    name: healthnova-ai-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    region: singapore
    plan: free
    healthCheckPath: /api/v1/health/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: healthnova-ai-backend.onrender.com,clinical-decision-support-system-20.vercel.app,clinical-decision-support-system-2026.vercel.app
      - key: CORS_ALLOWED_ORIGINS
        value: https://clinical-decision-support-system-20.vercel.app,https://clinical-decision-support-system-2026.vercel.app
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: REDIS_URL
        value: redis://localhost:6379
