# Generated by Django 5.0.14 on 2026-09-18 04:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JulesAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('actor_id', models.CharField(default='SYSTEM', max_length=100)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(db_index=True, max_length=60)),
                ('resource_id', models.CharField(db_index=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Jules Audit Event',
                'verbose_name_plural': 'Jules Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JulesSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('external_name', models.CharField(help_text='e.g. sources/github/owner/repo', max_length=255, unique=True)),
                ('source_id', models.CharField(db_index=True, max_length=120)),
                ('provider', models.CharField(default='github', max_length=50)),
                ('github_owner', models.CharField(max_length=100)),
                ('github_repository', models.CharField(max_length=150)),
                ('is_private', models.BooleanField(default=True)),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('available_branches', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jules Source',
                'verbose_name_plural': 'Jules Sources',
                'ordering': ['github_owner', 'github_repository'],
            },
        ),
        migrations.CreateModel(
            name='JulesRemediationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('correlation_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('repository', models.CharField(default='HealthNova-AI', max_length=200)),
                ('branch', models.CharField(default='develop', max_length=100)),
                ('trigger_type', models.CharField(choices=[('CI_FAILURE', 'GitHub Actions CI Failure'), ('REACT_DOCTOR', 'React Doctor Diagnostic'), ('BRUNO', 'Bruno API Test Failure'), ('STRIX', 'Strix Authorized Security Finding'), ('BUG_HUNTER', 'Agentic Bug Hunter Finding'), ('PENTEST_AGENTS', 'Pentest Agent Finding'), ('DJANGO_TEST', 'Django Test Failure'), ('NEXTJS_BUILD', 'Next.js Build Failure'), ('TYPESCRIPT', 'TypeScript Compile Failure'), ('LINT', 'Linter / Formatter Failure'), ('COOLIFY', 'Coolify Deployment Failure'), ('MANUAL', 'Manual Developer Request')], db_index=True, default='MANUAL', max_length=40)),
                ('issue_category', models.CharField(choices=[('BUILD_FAILURE', 'Build Failure'), ('TYPESCRIPT_ERROR', 'TypeScript Error'), ('PYTHON_ERROR', 'Python Error'), ('DJANGO_ERROR', 'Django Error'), ('DATABASE_ERROR', 'Database Error'), ('API_ERROR', 'API Error'), ('UI_ERROR', 'UI / React Error'), ('TEST_FAILURE', 'Test Failure'), ('LINT_FAILURE', 'Lint Failure'), ('PERFORMANCE_REGRESSION', 'Performance Regression'), ('ACCESSIBILITY_FAILURE', 'Accessibility Failure'), ('SECURITY_FINDING', 'Security Finding'), ('DEPENDENCY_FAILURE', 'Dependency Failure'), ('DOCKER_FAILURE', 'Docker Failure'), ('CI_FAILURE', 'CI Failure'), ('DEPLOYMENT_FAILURE', 'Deployment Failure'), ('DOCUMENTATION_FAILURE', 'Documentation Failure'), ('OTHER', 'Other')], db_index=True, default='BUILD_FAILURE', max_length=50)),
                ('issue_reference', models.CharField(blank=True, default='', help_text='e.g. Issue #142, CI Run #9928, Strix SEC-04', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_AUTHORIZATION', 'Pending Authorization'), ('AUTHORIZED', 'Authorized'), ('QUEUED', 'Queued'), ('JULES_SESSION_CREATED', 'Jules Session Created'), ('PLANNING', 'Planning'), ('PLAN_PENDING_APPROVAL', 'Plan Pending Approval'), ('EXECUTING', 'Executing'), ('VALIDATING', 'Validating'), ('AWAITING_REVIEW', 'Awaiting Review'), ('APPROVED', 'Approved'), ('PR_CREATED', 'PR Created'), ('MERGED', 'Merged'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=40)),
                ('validation_status', models.CharField(default='PENDING', max_length=20)),
                ('validation_output', models.JSONField(blank=True, default=dict)),
                ('pr_url', models.URLField(blank=True, default='', max_length=500)),
                ('pr_number', models.IntegerField(blank=True, null=True)),
                ('prompt_version', models.CharField(default='1.0', max_length=20)),
                ('remediation_attempts', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jules_jobs_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jules_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_jobs', to='jules.julessource')),
            ],
            options={
                'verbose_name': 'Jules Remediation Job',
                'verbose_name_plural': 'Jules Remediation Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JulesApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('approval_type', models.CharField(choices=[('PLAN_EXECUTION', 'Plan Execution Approval'), ('PR_CREATION', 'Pull Request Creation'), ('PR_MERGE', 'Pull Request Merge'), ('SENSITIVE_REMEDIATION', 'Sensitive Component Remediation')], default='PLAN_EXECUTION', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jules_approvals_granted', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jules_approvals_requested', to=settings.AUTH_USER_MODEL)),
                ('remediation_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='jules.julesremediationjob')),
            ],
            options={
                'verbose_name': 'Jules Approval',
                'verbose_name_plural': 'Jules Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JulesSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('external_session_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='Sanitized instruction sent to Jules')),
                ('repository', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('PLANNING', 'Generating Plan'), ('PLAN_PENDING_APPROVAL', 'Plan Pending Human Approval'), ('EXECUTING', 'Executing Code Remediation'), ('VALIDATING', 'Running Automated Validation'), ('AWAITING_REVIEW', 'Awaiting Engineer Review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=40)),
                ('automation_mode', models.CharField(default='NONE', max_length=40)),
                ('require_plan_approval', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jules_sessions', to=settings.AUTH_USER_MODEL)),
                ('remediation_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='jules.julesremediationjob')),
            ],
            options={
                'verbose_name': 'Jules Session',
                'verbose_name_plural': 'Jules Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JulesArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('artifact_type', models.CharField(default='PATCH', max_length=50)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('jules_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='jules.julessession')),
            ],
            options={
                'verbose_name': 'Jules Artifact',
                'verbose_name_plural': 'Jules Artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JulesActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('external_activity_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('activity_type', models.CharField(default='PROGRESS', help_text='e.g. PLAN_GENERATED, PROGRESS, MESSAGE, ARTIFACT', max_length=60)),
                ('originator', models.CharField(default='JULES', help_text='JULES, SYSTEM, or USER', max_length=40)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('jules_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='jules.julessession')),
            ],
            options={
                'verbose_name': 'Jules Activity',
                'verbose_name_plural': 'Jules Activities',
                'ordering': ['created_at'],
            },
        ),
    ]
