# Generated by Django 5.0.14 on 2026-09-13 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('HIGH', 'High Risk Alert'), ('CRITICAL', 'Critical / Emergency')], db_index=True, default='INFO', max_length=20)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App Notification'), ('WEBSOCKET', 'Real-Time WebSocket'), ('EMAIL', 'Email Alert'), ('SMS', 'SMS Dispatch')], default='IN_APP', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, help_text='Patient linked to this alert.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
                ('prediction', models.ForeignKey(blank=True, help_text='Prediction that triggered this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='predictions.prediction')),
                ('recipient', models.ForeignKey(help_text='Clinical staff member receiving this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'), models.Index(fields=['severity', 'created_at'], name='notificatio_severit_5abb00_idx')],
            },
        ),
    ]
