# Generated by Django 5.0.14 on 2026-09-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CLINICAL', 'Clinical Event'), ('RISK', 'Risk Assessment Alert'), ('TRIAGE', 'Triage Escalation'), ('APPOINTMENT', 'Appointment'), ('SYSTEM', 'System Alert'), ('SECURITY', 'Security Event'), ('AI', 'AI Assistant Output'), ('MODEL', 'Model Registry Alert'), ('DATA_QUALITY', 'Data Quality Anomaly'), ('ADMIN', 'Administrative Alert')], db_index=True, default='CLINICAL', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], db_index=True, default='UNREAD', max_length=20),
        ),
    ]
