# Generated by Django 5.0.14 on 2026-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PREDICT', 'Predict'), ('EXPORT', 'Export'), ('TRAIN', 'Train Model'), ('backup.created', 'Backup Created'), ('backup.validated', 'Backup Validated'), ('backup.failed', 'Backup Failed'), ('restore.started', 'Restore Started'), ('restore.completed', 'Restore Completed'), ('restore.failed', 'Restore Failed'), ('rollback.started', 'Rollback Started'), ('rollback.completed', 'Rollback Completed'), ('rollback.failed', 'Rollback Failed'), ('recovery.started', 'Recovery Started'), ('recovery.completed', 'Recovery Completed'), ('secret.rotated', 'Secret Rotated'), ('config.updated', 'Configuration Updated')], db_index=True, max_length=50),
        ),
    ]
