# Generated by Django 5.0.14 on 2026-09-15 12:25

import apps.security_testing.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('path', models.CharField(max_length=255)),
                ('http_method', models.CharField(default='GET', max_length=10)),
                ('auth_required', models.BooleanField(default=True)),
                ('role_required', models.CharField(default='IT_ADMIN', max_length=50)),
                ('is_discovered_dynamically', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('severity', models.CharField(default='INFO', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_endpoints_discovered', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('evidence_data', models.JSONField(default=dict)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_evidences', to='security_testing.reconfinding')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('param_name', models.CharField(max_length=100)),
                ('param_type', models.CharField(default='string', max_length=50)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='security_testing.reconendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reconfinding',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_findings', to='security_testing.reconsession'),
        ),
        migrations.AddField(
            model_name='reconendpoint',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='security_testing.reconsession'),
        ),
        migrations.CreateModel(
            name='ReconAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('asset_type', models.CharField(default='HOST', max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='security_testing.reconsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconTechnology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(default='Framework', max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='security_testing.reconsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('target_name', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('title', models.CharField(max_length=255)),
                ('vulnerability_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20)),
                ('state', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('TRIAGED', 'Triaged'), ('VALIDATION_REQUIRED', 'Validation Required'), ('VALIDATED', 'Validated (Confirmed Real Vulnerability)'), ('FALSE_POSITIVE', 'False Positive (Filtered Out)'), ('DUPLICATE', 'Duplicate'), ('REMEDIATION_REQUIRED', 'Remediation Required'), ('IN_PROGRESS', 'Remediation In Progress'), ('FIXED', 'Fix Implemented (Pending Retest)'), ('RETEST_REQUIRED', 'Retest Required'), ('RESOLVED', 'Resolved & Confirmed'), ('ACCEPTED_RISK', 'Accepted Risk by Authority'), ('REJECTED', 'Rejected by Validation Gate')], db_index=True, default='DISCOVERED', max_length=30)),
                ('confidence', models.FloatField(default=0.8, help_text='Deterministic confidence score (0.0 - 1.0)')),
                ('affected_component', models.CharField(max_length=255)),
                ('affected_endpoint', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('impact', models.TextField()),
                ('root_cause', models.TextField(blank=True)),
                ('remediation_guidance', models.TextField()),
                ('cwe_id', models.CharField(blank=True, help_text='e.g. CWE-639, CWE-79, CWE-89', max_length=50)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('discovered_by', models.CharField(default='AgenticBugHunterAdapter', max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_security_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('evidence_type', models.CharField(choices=[('HTTP_REQUEST', 'Redacted HTTP Request'), ('HTTP_RESPONSE', 'Redacted HTTP Response'), ('LOG_TRACE', 'Sanitized Log Trace'), ('REPRODUCTION_POC', 'Safe Reproduction Steps')], default='REPRODUCTION_POC', max_length=50)),
                ('sanitized_request', models.JSONField(default=dict)),
                ('sanitized_response', models.JSONField(default=dict)),
                ('reproduction_steps', models.TextField()),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='security_testing.securityfinding')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityRemediation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('pull_request_url', models.URLField(blank=True)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('remediation_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('FIXED', 'Fixed'), ('VERIFIED', 'Verified')], default='PENDING', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remediation', to='security_testing.securityfinding')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityRetest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('passed', models.BooleanField(default=False, help_text='True if original vulnerability is confirmed fixed and cannot be reproduced')),
                ('test_output', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retests', to='security_testing.securityfinding')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('scan_type', models.CharField(choices=[('RECON', 'Attack Surface & Route Recon'), ('API_SECURITY', 'API Security & Injection Testing'), ('RBAC_AUTH', '5-Role Privilege Escalation & Auth Matrix'), ('IDOR', 'Insecure Direct Object References'), ('SSRF_CHECK', 'Safe SSRF & Egress Boundary Check'), ('COMPREHENSIVE_LAB', 'Full Controlled Security Lab Scan')], default='API_SECURITY', max_length=50)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('APPROVAL_PENDING', 'Pending Dual-Custody Approval'), ('APPROVED', 'Approved'), ('QUEUED', 'Queued in Celery'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out'), ('BLOCKED', 'Blocked by Safety Policy')], db_index=True, default='CREATED', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('max_requests', models.IntegerField(default=100)),
                ('rate_limit_rps', models.FloatField(default=5.0)),
                ('timeout_seconds', models.IntegerField(default=300)),
                ('tools_used', models.JSONField(default=list)),
                ('raw_logs_sanitized', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_security_scans', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_security_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('report_type', models.CharField(choices=[('TECHNICAL_DEV', 'Technical Developer Report'), ('EXECUTIVE_AUDIT', 'Executive Audit Summary'), ('COMPLIANCE_HIPAA', 'HIPAA/SOC2 Security Posture')], default='TECHNICAL_DEV', max_length=50)),
                ('findings_summary', models.JSONField(default=dict)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_security_reports', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='security_testing.securityscan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='security_testing.securityscan'),
        ),
        migrations.CreateModel(
            name='SecurityTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(help_text='Human-readable target identifier', max_length=150, unique=True)),
                ('environment', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('SECURITY_TEST', 'Isolated Security Test Lab'), ('STAGING', 'Staging (Authorized Only)'), ('PRODUCTION', 'Production (Disabled by Default)')], db_index=True, default='SECURITY_TEST', max_length=30)),
                ('target_type', models.CharField(choices=[('APPLICATION', 'Full Application'), ('API', 'REST / JSON API'), ('WEB_FRONTEND', 'Next.js Web Frontend'), ('BACKEND', 'Django Backend'), ('MICROSERVICE', 'Microservice'), ('INTERNAL_SERVICE', 'Internal Service'), ('STAGING', 'Staging Target'), ('SECURITY_LAB', 'Local Security Lab'), ('LOCAL_DEMO', 'Local Synthetic Demo'), ('INTERNET_TARGET', 'External Target (Strict Admin Authorization Only)')], default='API', max_length=30)),
                ('hostname', models.CharField(help_text='Domain or IP address (e.g. localhost, 127.0.0.1, cdss-staging.internal)', max_length=255)),
                ('port', models.IntegerField(default=8000)),
                ('protocol', models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS'), ('ws', 'WebSocket'), ('wss', 'Secure WebSocket')], default='http', max_length=10)),
                ('scope', models.TextField(default='/api/v1/health/, /api/v1/predictions/, /api/v1/auth/', help_text='Explicit allowed scope paths, URLs or CIDRs (newline or JSON array)')),
                ('owner', models.CharField(default='DevSecOps Team', max_length=100)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Authorization'), ('APPROVED', 'Authorized'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Approval Expired'), ('REVOKED', 'Approval Revoked')], db_index=True, default='PENDING', max_length=20)),
                ('approval_expires_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_tests', models.JSONField(default=list, help_text="List of permitted test identifiers (e.g. ['RBAC_CHECK', 'IDOR_CHECK', 'XSS_CHECK', 'RATE_LIMIT_CHECK'])")),
                ('forbidden_tests', models.JSONField(default=apps.security_testing.models.default_forbidden_tests, help_text='Explicitly forbidden test operations')),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_security_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='securityscan',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='security_testing.securitytarget'),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='security_testing.securitytarget'),
        ),
        migrations.CreateModel(
            name='SecurityApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Authorization'), ('APPROVED', 'Authorized'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Approval Expired'), ('REVOKED', 'Approval Revoked')], default='PENDING', max_length=20)),
                ('scope_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security_testing.securityscan')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='security_testing.securitytarget')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='reconsession',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_sessions', to='security_testing.securitytarget'),
        ),
        migrations.CreateModel(
            name='SecurityToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_version', models.CharField(default='1.0.0', max_length=50)),
                ('execution_time_seconds', models.FloatField(default=0.0)),
                ('exit_code', models.IntegerField(default=0)),
                ('stdout_sanitized', models.TextField(blank=True)),
                ('stderr_sanitized', models.TextField(blank=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='security_testing.securityscan')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_target_authorized', models.BooleanField(default=True)),
                ('is_vulnerable', models.BooleanField(default=False)),
                ('is_reproducible', models.BooleanField(default=False)),
                ('is_exploitable', models.BooleanField(default=False)),
                ('has_meaningful_impact', models.BooleanField(default=False)),
                ('is_evidence_sufficient', models.BooleanField(default=False)),
                ('is_reportable', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('VALIDATED', 'Validated (Passed 7 Questions)'), ('FALSE_POSITIVE', 'False Positive Rejected'), ('INSUFFICIENT_EVIDENCE', 'Insufficient Evidence (Discarded)')], default='INSUFFICIENT_EVIDENCE', max_length=30)),
                ('validated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation', to='security_testing.securityfinding')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
