# Generated by Django 5.0.14 on 2026-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityfinding',
            name='clinical_impact',
            field=models.CharField(blank=True, choices=[('NONE', 'No Clinical Impact'), ('CONFIDENTIALITY', 'Patient Confidentiality Risk'), ('INTEGRITY', 'Clinical Data Integrity Risk'), ('AVAILABILITY', 'Service Availability Risk'), ('PREDICTION_INTEGRITY', 'ML Prediction Integrity Risk'), ('AUDIT_INTEGRITY', 'Audit Log Integrity Risk')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Deterministic SHA-256 fingerprint for cross-scan deduplication', max_length=64),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='is_regression',
            field=models.BooleanField(default=False, help_text='True if this is a re-occurrence of a previously fixed finding'),
        ),
        migrations.AddField(
            model_name='securityfinding',
            name='organizational_risk',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFORMATIONAL', 'Informational')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='actual_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='authorization_snapshot',
            field=models.JSONField(default=dict, help_text='Snapshot of authorization state at scan creation'),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='budget_limit',
            field=models.FloatField(default=10.0, help_text='Maximum LLM cost budget in USD'),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='coverage_status',
            field=models.CharField(choices=[('FULL', 'Full Coverage'), ('PARTIAL', 'Partial Coverage'), ('INCONCLUSIVE', 'Inconclusive'), ('NOT_STARTED', 'Not Started')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='sarif_artifact_path',
            field=models.CharField(blank=True, help_text='Relative path to SARIF 2.1.0 artifact', max_length=512),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='scan_mode',
            field=models.CharField(blank=True, choices=[('QUICK_SECURITY_REVIEW', 'Quick Security Review'), ('STANDARD_SECURITY_ASSESSMENT', 'Standard Security Assessment'), ('DEEP_SECURITY_ASSESSMENT', 'Deep Security Assessment')], default='STANDARD_SECURITY_ASSESSMENT', max_length=40),
        ),
        migrations.AddField(
            model_name='securityscan',
            name='strix_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
