# Generated by Django 5.0.14 on 2026-09-17 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_testing', '0002_strix_integration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPToolRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(help_text='MCP Tool Identifier (e.g. mcp_bounty_search)', max_length=100, unique=True)),
                ('description', models.TextField()),
                ('risk', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='HIGH', max_length=20)),
                ('permissions', models.JSONField(default=list, help_text='Required user/system permissions')),
                ('allowed_roles', models.JSONField(default=list, help_text="Allowed agent roles (e.g. ['REPORT_WRITER', 'RECON'])")),
                ('allowed_targets', models.JSONField(default=list, help_text="Target names or '*' if governed by target authorization")),
                ('network_scope', models.CharField(choices=[('LOCAL_ONLY', 'Local Sandbox Only'), ('TARGET_ONLY', 'Authorized Target Network'), ('BLOCKED', 'Network Access Blocked')], default='BLOCKED', max_length=30)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('RESTRICTED', 'Restricted (No Secrets/PHI)')], default='RESTRICTED', max_length=30)),
                ('approval_requirement', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Explicit enable switch (Default DENY)')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAgentCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('capability', models.CharField(choices=[('RECON', 'Reconnaissance'), ('SAST', 'Static Application Security Testing'), ('API_TESTING', 'API Endpoint Security Testing'), ('AUTH_TESTING', 'Authorization Matrix Testing'), ('IDOR', 'Insecure Direct Object Reference'), ('RCE_ANALYSIS', 'Remote Code Execution Analysis'), ('SSRF_ANALYSIS', 'SSRF Boundary Analysis'), ('XSS_ANALYSIS', 'Cross-Site Scripting Analysis'), ('WEB3_ANALYSIS', 'Web3 / Cryptographic Key Testing'), ('EXPLOIT_CHAINING', 'Safe Multi-step Exploit Chaining Analysis'), ('WRITEUP_ANALYSIS', 'Approved Bug Bounty Writeup Search'), ('REPORT_GENERATION', 'Standardized Security Report Drafting')], max_length=40, unique=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=20)),
                ('required_permission', models.CharField(default='SECURITY_AGENT_RUN', max_length=100)),
                ('allowed_environment', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('SECURITY_TEST', 'Isolated Security Test Lab'), ('STAGING', 'Staging (Authorized Only)'), ('PRODUCTION', 'Production (Disabled by Default)')], default='SECURITY_TEST', max_length=30)),
                ('network_policy', models.CharField(choices=[('NONE', 'No Network (Isolated Sandbox)'), ('RESTRICTED', 'Restricted to Target Host Only'), ('TARGET_ONLY', 'Direct Target Port Only')], default='NONE', max_length=30)),
                ('approval_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityAgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('provider', models.CharField(choices=[('STRIX', 'Strix AI Security Engine'), ('AGENTIC_BUGHUNTER', 'Agentic Bug Hunter Toolkit'), ('PENTEST_AGENTS', 'H-mmer Pentest-Agents Framework')], db_index=True, default='PENTEST_AGENTS', max_length=30)),
                ('agent', models.CharField(choices=[('RECON', 'Reconnaissance Agent'), ('SAST', 'Static Application Security Testing Agent'), ('API_SECURITY', 'API Security Agent'), ('AUTH_SECURITY', 'Authorization & RBAC Agent'), ('IDOR', 'IDOR Detection Agent'), ('INPUT_VALIDATION', 'Input Validation Agent'), ('WEB_SECURITY', 'Web Security Agent'), ('CLOUD_SECURITY', 'Cloud Security Agent'), ('AI_SECURITY', 'AI & Prompt Security Agent'), ('VALIDATOR', '7-Question Validation Agent'), ('REPORT_WRITER', 'Report Drafting Agent'), ('DUPLICATE_CHECKER', 'Duplicate Detection Agent')], db_index=True, default='API_SECURITY', max_length=40)),
                ('task', models.CharField(help_text='Specific testing task or objective', max_length=255)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('AUTHORIZED', 'Authorized'), ('QUEUED', 'Queued in Celery'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('WAITING_APPROVAL', 'Waiting for Approval'), ('VALIDATING', 'Validating Output'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PLANNED', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('token_usage', models.JSONField(default=dict, help_text="Token usage breakdown: {'prompt_tokens': 0, 'completion_tokens': 0, 'total_tokens': 0, 'estimated_cost': 0.0}")),
                ('tool_calls', models.JSONField(default=list, help_text='Sanitized chronological audit trail of agent tool calls')),
                ('result', models.JSONField(default=dict, help_text='Normalized agent execution findings and output')),
                ('error', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='Distributed tracing correlation ID', max_length=64)),
                ('workspace_path', models.CharField(blank=True, help_text='Path to ephemeral workspace directory in security_workspaces/', max_length=512)),
                ('assessment', models.ForeignKey(help_text='Parent security assessment / scan', on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='security_testing.securityscan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityFindingCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('cluster_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('vulnerability_type', models.CharField(db_index=True, max_length=100)),
                ('affected_endpoint', models.CharField(max_length=255)),
                ('providers', models.JSONField(default=list, help_text="List of providers that confirmed this finding (e.g. ['STRIX', 'PENTEST_AGENTS'])")),
                ('confidence_score', models.FloatField(default=0.8)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('TRIAGED', 'Triaged'), ('VALIDATION_REQUIRED', 'Validation Required'), ('VALIDATED', 'Validated (Confirmed Real Vulnerability)'), ('FALSE_POSITIVE', 'False Positive (Filtered Out)'), ('DUPLICATE', 'Duplicate'), ('REMEDIATION_REQUIRED', 'Remediation Required'), ('IN_PROGRESS', 'Remediation In Progress'), ('FIXED', 'Fix Implemented (Pending Retest)'), ('RETEST_REQUIRED', 'Retest Required'), ('RESOLVED', 'Resolved & Confirmed'), ('ACCEPTED_RISK', 'Accepted Risk by Authority'), ('REJECTED', 'Rejected by Validation Gate')], default='TRIAGED', max_length=30)),
                ('findings', models.ManyToManyField(blank=True, related_name='finding_clusters', to='security_testing.securityfinding')),
                ('primary_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cluster', to='security_testing.securityfinding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
