"""
AI Safety Guardrails and Clinical Policy Enforcement.
Protects the system from prompt injection, authority usurpation,
and autonomous clinical diagnoses or prescription orders.
"""
import re
from typing import List, Tuple

from services.interfaces import GuardrailResult, ISafetyGuardrail

# Explicit prompt injection & jailbreak indicators
PROMPT_INJECTION_PATTERNS = [
    r"ignore\s+(all\s+)?(previous|prior)\s+instructions",
    r"system\s+prompt\s+override",
    r"you\s+are\s+now\s+(an\s+)?unrestricted",
    r"dan\s+mode",
    r"jailbreak",
    r"bypass\s+safety\s+filter",
    r"developer\s+mode\s+enabled",
    r"disregard\s+all\s+clinical\s+rules",
    r"execute\s+(shell|bash|sql|command)",
    r"drop\s+table",
    r"select\s+\*\s+from\s+auth_user",
]

# Strict prohibitions for clinical decision support systems
AUTONOMOUS_DIAGNOSIS_PATTERNS = [
    r"\bi\s+(hereby\s+)?diagnose\b",
    r"\bthe\s+definitive\s+diagnosis\s+is\b",
    r"\bi\s+prescribe\b",
    r"\bprescribing\s+\d+\s*mg\b",
    r"\bdischarge\s+the\s+patient\s+immediately\b",
    r"\bdiscontinue\s+all\s+medications\b",
    r"\bno\s+doctor\s+needed\b",
]

MANDATORY_CLINICAL_DISCLAIMER = (
    "\n\n[CLINICAL DECISION SUPPORT NOTICE: This assessment is generated by an automated "
    "decision-support system to assist qualified healthcare professionals. It does NOT "
    "constitute a medical diagnosis, therapeutic prescription, or clinical order. "
    "All recommendations require evaluation by a licensed healthcare provider.]"
)


class SafetyGuardrailService(ISafetyGuardrail):
    """
    Validates input queries and assistant outputs against security and medical safety policies.
    """

    def validate_input(self, text: str, user_role: str) -> GuardrailResult:
        """
        Validate user input against prompt injection, jailbreaks, and role authorization.
        """
        if not text or not text.strip():
            return GuardrailResult(is_safe=False, reason="Input query cannot be empty.")

        flags: List[str] = []

        # Check for adversarial prompt injection patterns
        for pattern in PROMPT_INJECTION_PATTERNS:
            if re.search(pattern, text, re.IGNORECASE):
                flags.append("PROMPT_INJECTION_SUSPICION")
                return GuardrailResult(
                    is_safe=False,
                    reason="Input contains disallowed instruction override or prompt injection attempt.",
                    flags=flags,
                )

        # Check for cross-patient data access attempts in text
        if re.search(r"all\s+patients|dump\s+database|show\s+other\s+records", text, re.IGNORECASE):
            flags.append("BULK_EXFILTRATION_ATTEMPT")
            return GuardrailResult(
                is_safe=False,
                reason="Bulk or unauthorized patient data queries are strictly prohibited.",
                flags=flags,
            )

        sanitized = re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]", "", text).strip()
        return GuardrailResult(is_safe=True, sanitized_input=sanitized, flags=flags)

    def validate_output(self, output: str) -> GuardrailResult:
        """
        Ensure AI output never impersonates a diagnostic authority or issues prescriptions.
        Appends mandatory CDSS disclaimer.
        """
        if not output:
            return GuardrailResult(is_safe=False, reason="AI output was empty.")

        flags: List[str] = []

        for pattern in AUTONOMOUS_DIAGNOSIS_PATTERNS:
            if re.search(pattern, output, re.IGNORECASE):
                flags.append("AUTONOMOUS_DIAGNOSIS_VIOLATION")
                return GuardrailResult(
                    is_safe=False,
                    reason=(
                        "Safety policy violation: AI output attempted to issue an autonomous diagnosis, "
                        "prescription, or medical order. Output suppressed by safety guardrails."
                    ),
                    flags=flags,
                )

        # Enforce disclaimer presence
        if "CLINICAL DECISION SUPPORT NOTICE" not in output:
            safe_output = output + MANDATORY_CLINICAL_DISCLAIMER
        else:
            safe_output = output

        return GuardrailResult(
            is_safe=True,
            sanitized_input=safe_output,
            flags=flags,
        )
