# Generated by Django 5.0.14 on 2026-09-17 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalWhiteboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('CARE_PLAN', 'Care Plan'), ('CLINICAL_WORKFLOW', 'Clinical Workflow'), ('PATIENT_JOURNEY', 'Patient Journey'), ('TRIAGE_WORKFLOW', 'Triage Workflow'), ('RISK_ANALYSIS', 'Risk Analysis'), ('DECISION_TREE', 'Decision Tree'), ('CLINICAL_EDUCATION', 'Clinical Education'), ('TEAM_COLLABORATION', 'Team Collaboration'), ('ML_WORKFLOW', 'ML Workflow'), ('AI_WORKFLOW', 'AI Workflow'), ('DATA_LINEAGE', 'Data Lineage'), ('SYSTEM_ARCHITECTURE', 'System Architecture'), ('INCIDENT_RESPONSE', 'Incident Response'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=50)),
                ('classification', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('SENSITIVE', 'Sensitive'), ('PHI', 'Protected Health Information (PHI)'), ('RESTRICTED', 'Restricted')], db_index=True, default='INTERNAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('DELETED_PENDING_RETENTION', 'Deleted Pending Retention'), ('PURGED', 'Purged')], db_index=True, default='DRAFT', max_length=30)),
                ('organization_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_version', models.IntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary clinical or ML references, non-authoritative annotations.')),
                ('thumbnail_data', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_whiteboards', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whiteboards', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_whiteboards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_whiteboards', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text='Optional linked patient record. Enforces PHI classification when set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_whiteboards', to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_whiteboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_whiteboards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='whiteboards/assets/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField(default=0)),
                ('sha256_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='whiteboards.clinicalwhiteboard')),
            ],
            options={
                'db_table': 'whiteboard_assets',
            },
        ),
        migrations.CreateModel(
            name='WhiteboardAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(blank=True, default='', max_length=50)),
                ('action', models.CharField(db_index=True, max_length=50)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_audit_events', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='whiteboards.clinicalwhiteboard')),
            ],
            options={
                'db_table': 'whiteboard_audit_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('element_id', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_comments', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='whiteboards.clinicalwhiteboard')),
            ],
            options={
                'db_table': 'whiteboard_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(db_index=True)),
                ('elements', models.JSONField(default=list, help_text='Excalidraw elements array')),
                ('app_state', models.JSONField(blank=True, default=dict, help_text='Excalidraw appState dictionary')),
                ('files', models.JSONField(blank=True, default=dict, help_text='Excalidraw binary files mapping')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.IntegerField(default=0)),
                ('schema_version', models.IntegerField(default=2)),
                ('is_checkpoint', models.BooleanField(default=False)),
                ('checkpoint_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboard_documents', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='whiteboards.clinicalwhiteboard')),
            ],
            options={
                'db_table': 'whiteboard_documents',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('client_color', models.CharField(default='#0284c7', max_length=20)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_sessions', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='whiteboards.clinicalwhiteboard')),
            ],
            options={
                'db_table': 'whiteboard_sessions',
            },
        ),
        migrations.CreateModel(
            name='WhiteboardShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('target_role', models.CharField(blank=True, default='', max_length=50)),
                ('allow_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whiteboard_shares', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_whiteboard_shares', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='whiteboards.clinicalwhiteboard')),
            ],
            options={
                'db_table': 'whiteboard_shares',
            },
        ),
        migrations.AddIndex(
            model_name='clinicalwhiteboard',
            index=models.Index(fields=['type', 'classification'], name='clinical_wh_type_fb621f_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalwhiteboard',
            index=models.Index(fields=['status', 'updated_at'], name='clinical_wh_status_6a2e98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whiteboarddocument',
            unique_together={('whiteboard', 'version_number')},
        ),
    ]
