# Generated by Django 5.0.14 on 2026-09-17 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringLoopBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(default='Global Engineering Loop Budget', max_length=100)),
                ('daily_limit', models.FloatField(default=15.0, help_text='Daily limit in USD')),
                ('weekly_limit', models.FloatField(default=75.0, help_text='Weekly limit in USD')),
                ('per_run_limit', models.FloatField(default=2.0, help_text='Max cost per single run in USD')),
                ('per_agent_limit', models.FloatField(default=1.0, help_text='Max cost per agent session in USD')),
                ('current_daily_spend', models.FloatField(default=0.0)),
                ('current_weekly_spend', models.FloatField(default=0.0)),
                ('hard_stop', models.BooleanField(default=True, help_text='Halt execution when limit reached')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineeringToolRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('risk', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('allowed_roles', models.JSONField(default=list)),
                ('allowed_autonomy', models.CharField(choices=[('L1_REPORT_ONLY', 'L1 — Report Only (Discover & Triage)'), ('L2_ASSISTED', 'L2 — Assisted (Propose Patch & Tests, Human Gate)'), ('L3_CONTROLLED_UNATTENDED', 'L3 — Controlled Unattended (Explicit Allowlist Only)')], default='L1_REPORT_ONLY', max_length=30)),
                ('allowed_paths', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineeringLoop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('repository', models.CharField(default='clinical-decision-support-system', max_length=255)),
                ('pattern', models.CharField(choices=[('DAILY_TRIAGE', 'Daily Engineering Triage'), ('THIN_LOOP', 'Thin Scoped Loop'), ('PR_BABYSITTER', 'PR Babysitter'), ('CI_SWEEPER', 'CI Failure Sweeper'), ('DEPENDENCY_SWEEPER', 'Dependency Security Sweeper'), ('CHANGELOG_DRAFTER', 'Changelog Drafter'), ('POST_MERGE_CLEANUP', 'Post-Merge Branch Cleanup'), ('ISSUE_TRIAGE', 'Issue Triage & Classification'), ('CLINICAL_CODE_HEALTH', 'Clinical Code & Safety Check (L1)'), ('ML_REGRESSION_CHECK', 'ML Regression & Model Drift (L1)'), ('DOCUMENTATION_SYNC', 'Documentation & Spec Drift Check'), ('SPEC_CONVERGENCE', 'Spec Kit Convergence Audit')], db_index=True, default='DAILY_TRIAGE', max_length=50)),
                ('tool', models.CharField(default='@cobusgreyling/loop', max_length=100)),
                ('cadence', models.CharField(choices=[('MANUAL', 'On Demand / Manual'), ('DAILY', 'Daily Scheduled'), ('HOURLY', 'Hourly Scheduled'), ('CI_EVENT', 'CI / Pipeline Trigger'), ('PR_EVENT', 'Pull Request Trigger'), ('DEPENDENCY_EVENT', 'Dependency Update Trigger')], default='MANUAL', max_length=30)),
                ('autonomy_level', models.CharField(choices=[('L1_REPORT_ONLY', 'L1 — Report Only (Discover & Triage)'), ('L2_ASSISTED', 'L2 — Assisted (Propose Patch & Tests, Human Gate)'), ('L3_CONTROLLED_UNATTENDED', 'L3 — Controlled Unattended (Explicit Allowlist Only)')], db_index=True, default='L1_REPORT_ONLY', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Definition'), ('VALIDATING', 'Validating Constraints'), ('READY', 'Ready for Execution'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued in Celery'), ('RUNNING', 'Running in Worktree'), ('VERIFYING', 'Maker/Checker Verification'), ('WAITING_APPROVAL', 'Waiting for Dual-Custody Approval'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired')], db_index=True, default='READY', max_length=30)),
                ('allowed_paths', models.JSONField(default=list, help_text='Explicit allowed paths in repository')),
                ('denied_paths', models.JSONField(default=list, help_text='Explicit denied paths (e.g. .env, clinical models, secrets)')),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_engineering_loops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringLoopRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Definition'), ('VALIDATING', 'Validating Constraints'), ('READY', 'Ready for Execution'), ('SCHEDULED', 'Scheduled'), ('QUEUED', 'Queued in Celery'), ('RUNNING', 'Running in Worktree'), ('VERIFYING', 'Maker/Checker Verification'), ('WAITING_APPROVAL', 'Waiting for Dual-Custody Approval'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired')], db_index=True, default='QUEUED', max_length=30)),
                ('trigger', models.CharField(default='MANUAL', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('cost_estimate', models.FloatField(default=0.0)),
                ('actual_cost', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=1)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('worktree_path', models.CharField(blank=True, max_length=512)),
                ('summary', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('loop_ready_score', models.IntegerField(default=0, help_text='Retrieved from upstream @cobusgreyling/loop doctor/audit')),
                ('findings_count', models.IntegerField(default=0)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='engineering_loops.engineeringloop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringLoopAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineering_loops.engineeringloop')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engineering_loops.engineeringlooprun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EngineeringLoopArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('artifact_type', models.CharField(default='REPORT', max_length=50)),
                ('path', models.CharField(max_length=512)),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='engineering_loops.engineeringlooprun')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineeringLoopApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('approval_type', models.CharField(default='PATCH_MERGE', max_length=50)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('scope_notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_loop_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_loop_approvals', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='engineering_loops.engineeringlooprun')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngineeringLoopTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('task_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('assigned_agent', models.CharField(default='LoopEngine', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_data', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='engineering_loops.engineeringlooprun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
