# Generated by Django 5.0.14 on 2026-09-15 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=255)),
                ('category', models.CharField(default='Health', max_length=100)),
                ('description', models.TextField()),
                ('base_url', models.URLField(max_length=500)),
                ('documentation_url', models.URLField(blank=True, max_length=500)),
                ('authentication_type', models.CharField(choices=[('NONE', 'No Authentication'), ('API_KEY', 'API Key'), ('BEARER', 'Bearer Token'), ('OAUTH2', 'OAuth 2.0'), ('BASIC', 'Basic Auth')], default='NONE', max_length=50)),
                ('https_required', models.BooleanField(default=True)),
                ('cors_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='YES', max_length=20)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('UNDER_REVIEW', 'Under Review'), ('SECURITY_REVIEW', 'Security Review'), ('PRIVACY_REVIEW', 'Privacy Review'), ('CLINICAL_REVIEW', 'Clinical Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEPRECATED', 'Deprecated'), ('REJECTED', 'Rejected')], db_index=True, default='DISCOVERED', max_length=50)),
                ('trust_level', models.CharField(choices=[('UNTRUSTED', 'Untrusted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('CLINICAL_APPROVED', 'Clinical Approved')], default='UNTRUSTED', max_length=50)),
                ('approved_for_use', models.BooleanField(default=False)),
                ('clinical_relevance', models.TextField(blank=True)),
                ('data_classification', models.CharField(default='PUBLIC', max_length=50)),
                ('rate_limit', models.CharField(default='240 req/min', max_length=100)),
                ('timeout', models.PositiveIntegerField(default=5, help_text='Timeout in seconds')),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('UNHEALTHY', 'Unhealthy'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External API Registry',
                'verbose_name_plural': 'External API Registries',
                'db_table': 'external_api_registry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAPILicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=255)),
                ('api_name', models.CharField(max_length=255)),
                ('license', models.CharField(default='Open Data / Public Domain', max_length=255)),
                ('terms_url', models.URLField(blank=True, max_length=500)),
                ('documentation_url', models.URLField(blank=True, max_length=500)),
                ('review_status', models.CharField(default='REVIEWED', max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_api_licenses',
            },
        ),
        migrations.CreateModel(
            name='ExternalAPIHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('status_code', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='external_apis.externalapiregistry')),
            ],
            options={
                'db_table': 'external_api_health',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAPIAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=500)),
                ('http_method', models.CharField(default='GET', max_length=10)),
                ('request_id', models.CharField(db_index=True, max_length=100)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('status_code', models.IntegerField(default=200)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=True)),
                ('circuit_state', models.CharField(default='CLOSED', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='external_apis.externalapiregistry')),
            ],
            options={
                'db_table': 'external_api_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAPIApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('UNDER_REVIEW', 'Under Review'), ('SECURITY_REVIEW', 'Security Review'), ('PRIVACY_REVIEW', 'Privacy Review'), ('CLINICAL_REVIEW', 'Clinical Review'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEPRECATED', 'Deprecated'), ('REJECTED', 'Rejected')], max_length=50)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested')], max_length=50)),
                ('reviewer_role', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_api_approvals', to=settings.AUTH_USER_MODEL)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='external_apis.externalapiregistry')),
            ],
            options={
                'db_table': 'external_api_approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
