# Generated by Django 5.0.14 on 2026-09-13 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Role name (e.g. ADMIN, DOCTOR, NURSE, ANALYST).', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of clinical responsibilities and access level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_obj',
            field=models.ForeignKey(blank=True, help_text='Normalized relational role foreign key.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='accounts.role'),
        ),
    ]
