# Generated by Django 5.0.14 on 2026-09-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_user_role_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CLINICIAN', 'Clinician'), ('STAFF', 'Staff'), ('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('ANALYST', 'Analyst')], db_index=True, default='DOCTOR', help_text='Clinical role determining access permissions.', max_length=20),
        ),
    ]
