# Generated by Django 5.0.14 on 2026-09-13 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('codename', models.CharField(db_index=True, help_text='Unique permission code (e.g. doctor.prediction.review, nurse.vitals.create).', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission label.', max_length=150)),
                ('category', models.CharField(db_index=True, help_text='Permission domain: clinical, prediction, triage, informatics, admin.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed capability description.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clinical Permission',
                'verbose_name_plural': 'Clinical Permissions',
                'db_table': 'clinical_permissions',
                'ordering': ['category', 'codename'],
            },
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, help_text='Role name (e.g. DOCTOR, NURSE, MEDICAL_INFORMATICIST, IT_ADMIN).', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DOCTOR', 'Doctor / Physician'), ('NURSE', 'Triage / Bedside Nurse'), ('MEDICAL_INFORMATICIST', 'Medical Informaticist'), ('IT_ADMIN', 'IT System Administrator'), ('ADMIN', 'Administrator'), ('CLINICIAN', 'Clinician'), ('STAFF', 'Staff'), ('PATIENT', 'Patient'), ('ANALYST', 'Analyst')], db_index=True, default='DOCTOR', help_text='Clinical role determining access permissions.', max_length=50),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.clinicalpermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
