# Generated by Django 5.0.14 on 2026-09-21 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIREndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('name', models.CharField(db_index=True, help_text='Human-readable hospital or partner system name (e.g. MetroHealth Epic).', max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='FHIR R4 base endpoint URL (e.g. https://ehr.metrohealth.org/fhir/r4).', max_length=500)),
                ('fhir_version', models.CharField(default='4.0.1', help_text='Supported FHIR specification release (e.g. 4.0.1).', max_length=20)),
                ('auth_type', models.CharField(choices=[('NONE', 'No Authentication (Sandbox / Public)'), ('API_KEY', 'API Key / Header Token'), ('BEARER', 'Bearer JWT Token'), ('SMART_ON_FHIR', 'SMART on FHIR (OAuth2)'), ('MUTUAL_TLS', 'Mutual TLS (mTLS)')], default='BEARER', max_length=30)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Encrypted or sanitized authentication metadata (client_id, scopes, headers).')),
                ('trust_level', models.CharField(choices=[('UNTRUSTED', 'Untrusted / Sandbox'), ('REVIEWED', 'Reviewed Partner System'), ('APPROVED_RESTRICTED', 'Approved (Read Only / Restricted)'), ('AUTHORITATIVE_PARTNER', 'Authoritative Clinical Partner (EHR/HIE)')], db_index=True, default='REVIEWED', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this external endpoint is actively permitted for data exchange.')),
                ('allowed_direction', models.CharField(choices=[('INBOUND_IMPORT', 'Inbound Import (External -> HealthNova)'), ('OUTBOUND_EXPORT', 'Outbound Export (HealthNova -> External)'), ('BI_DIRECTIONAL', 'Bi-directional Synchronization')], default='BI_DIRECTIONAL', max_length=30)),
                ('sync_schedule_cron', models.CharField(blank=True, default='0 */6 * * *', help_text='Cron expression for automated background sync (e.g. every 6 hours).', max_length=50)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120, help_text='Maximum allowed requests per minute to protect internal and external servers.')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, help_text='HTTP timeout in seconds.')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Timestamp of most recent synchronization attempt.', null=True)),
                ('health_status', models.CharField(default='HEALTHY', help_text='Current endpoint connectivity health (HEALTHY, DEGRADED, UNHEALTHY).', max_length=30)),
            ],
            options={
                'verbose_name': 'FHIR Endpoint',
                'verbose_name_plural': 'FHIR Endpoints',
                'db_table': 'fhir_endpoints',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FHIRSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('direction', models.CharField(choices=[('INBOUND_IMPORT', 'Inbound Import (External -> HealthNova)'), ('OUTBOUND_EXPORT', 'Outbound Export (HealthNova -> External)'), ('BI_DIRECTIONAL', 'Bi-directional Synchronization')], db_index=True, default='INBOUND_IMPORT', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed Successfully'), ('PARTIAL_SUCCESS', 'Completed with Partial Failures'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('resources_requested', models.JSONField(default=list, help_text="List of FHIR resource types requested for sync (e.g. ['Patient', 'Observation']).")),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('imported_records', models.PositiveIntegerField(default=0)),
                ('exported_records', models.PositiveIntegerField(default=0)),
                ('conflicts_generated', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.DecimalField(decimal_places=2, default=0.0, help_text='Total execution duration in milliseconds.', max_digits=10)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_jobs', to='interoperability.fhirendpoint')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_fhir_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHIR Sync Job',
                'verbose_name_plural': 'FHIR Sync Jobs',
                'db_table': 'fhir_sync_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRProvenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, help_text="Internal model name (e.g. 'Patient', 'ClinicalRecord', 'Prediction').", max_length=100)),
                ('entity_id', models.CharField(db_index=True, help_text='Primary key UUID of the internal domain record in Neon PostgreSQL.', max_length=100)),
                ('external_system_name', models.CharField(db_index=True, max_length=255)),
                ('external_resource_id', models.CharField(db_index=True, help_text='ID of the resource in the external FHIR server.', max_length=255)),
                ('external_version_id', models.CharField(blank=True, max_length=50)),
                ('fhir_resource_type', models.CharField(db_index=True, help_text='FHIR resource type (e.g. Patient, Observation, Encounter).', max_length=50)),
                ('payload_sha256', models.CharField(db_index=True, help_text='SHA-256 checksum of the raw external FHIR JSON payload.', max_length=64)),
                ('raw_payload_snapshot', models.JSONField(default=dict, help_text='Sanitized snapshot of the incoming/outgoing FHIR payload.')),
                ('direction', models.CharField(choices=[('INBOUND_IMPORT', 'Inbound Import (External -> HealthNova)'), ('OUTBOUND_EXPORT', 'Outbound Export (HealthNova -> External)'), ('BI_DIRECTIONAL', 'Bi-directional Synchronization')], default='INBOUND_IMPORT', max_length=30)),
                ('actor_reference', models.CharField(blank=True, help_text='Originating practitioner, device, or system identity.', max_length=255)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_records', to='interoperability.fhirendpoint')),
                ('sync_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_records', to='interoperability.fhirsyncjob')),
            ],
            options={
                'verbose_name': 'FHIR Provenance Record',
                'verbose_name_plural': 'FHIR Provenance Records',
                'db_table': 'fhir_provenance_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, max_length=20)),
                ('operation', models.CharField(db_index=True, help_text='HTTP method and FHIR resource path (e.g. POST /Patient, GET /Observation).', max_length=100)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status_code', models.PositiveIntegerField()),
                ('is_success', models.BooleanField(db_index=True, default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('duration_ms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fhir_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='interoperability.fhirendpoint')),
            ],
            options={
                'verbose_name': 'FHIR Audit Log',
                'verbose_name_plural': 'FHIR Audit Logs',
                'db_table': 'fhir_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['direction', 'timestamp'], name='fhir_audit__directi_f8165f_idx'), models.Index(fields=['resource_type', 'is_success'], name='fhir_audit__resourc_01a4fc_idx'), models.Index(fields=['correlation_id'], name='fhir_audit__correla_bbb10f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FHIRMappingConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('conflict_type', models.CharField(choices=[('DUPLICATE_PATIENT_MATCH', 'Probabilistic Duplicate Patient Match'), ('AMBIGUOUS_MAPPING', 'Ambiguous Clinical Field Mapping'), ('VALUE_OUT_OF_BOUNDS', 'Physiologically Invalid / Out of Bounds'), ('OVERWRITE_PROTECTION_TRIGGERED', 'Authoritative Overwrite Protection Triggered'), ('UNRECOGNIZED_CODE', 'Unrecognized Terminology / Code System'), ('INTEGRITY_VIOLATION', 'Cryptographic or Provenance Integrity Violation')], db_index=True, default='OVERWRITE_PROTECTION_TRIGGERED', max_length=50)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Human Clinician / Informaticist Review'), ('IN_REVIEW', 'Under Active Investigation'), ('APPROVED_APPLY', 'Approved & Applied to Authoritative Store'), ('REJECTED', 'Rejected by Reviewer'), ('DISMISSED', 'Dismissed (Benign / Irrelevant)')], db_index=True, default='PENDING_REVIEW', max_length=30)),
                ('resource_type', models.CharField(db_index=True, help_text='FHIR resource type involved (e.g. Patient, Observation).', max_length=50)),
                ('incoming_payload', models.JSONField(help_text='The raw incoming FHIR resource payload.')),
                ('existing_entity_type', models.CharField(blank=True, help_text="Internal model name of existing record (e.g. 'Patient').", max_length=100)),
                ('existing_entity_id', models.CharField(blank=True, help_text='Primary key UUID of the existing internal record in Neon.', max_length=100)),
                ('discrepancy_details', models.JSONField(default=dict, help_text='Structured side-by-side diff between incoming values and existing authoritative values.')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, help_text='Match confidence score for probabilistic duplicates (0.0000 - 1.0000).', max_digits=5, null=True)),
                ('resolution_action', models.CharField(blank=True, choices=[('OVERWRITE_EXISTING', 'Overwrite Authoritative Internal Record'), ('MERGE_RECORDS', 'Merge Non-Conflicting Attributes'), ('CREATE_NEW_RECORD', 'Create Disjoint Internal Record'), ('REJECT_INCOMING', 'Reject Incoming Payload Without Modification')], help_text='Action selected by human reviewer.', max_length=50, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Clinical justification and reasoning provided by human reviewer.')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Clinician or informaticist assigned to review this conflict.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fhir_conflicts', to=settings.AUTH_USER_MODEL)),
                ('external_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='interoperability.fhirendpoint')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fhir_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FHIR Mapping Conflict',
                'verbose_name_plural': 'FHIR Mapping Conflicts',
                'db_table': 'fhir_mapping_conflicts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'conflict_type'], name='fhir_mappin_status_1e2e50_idx'), models.Index(fields=['resource_type', 'status'], name='fhir_mappin_resourc_b43e97_idx'), models.Index(fields=['existing_entity_type', 'existing_entity_id'], name='fhir_mappin_existin_4d5e07_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='fhirsyncjob',
            index=models.Index(fields=['status', 'created_at'], name='fhir_sync_j_status_0979fb_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirsyncjob',
            index=models.Index(fields=['endpoint', 'created_at'], name='fhir_sync_j_endpoin_4860e1_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirprovenancerecord',
            index=models.Index(fields=['entity_type', 'entity_id'], name='fhir_proven_entity__305ffc_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirprovenancerecord',
            index=models.Index(fields=['external_system_name', 'external_resource_id'], name='fhir_proven_externa_ba3565_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirprovenancerecord',
            index=models.Index(fields=['payload_sha256'], name='fhir_proven_payload_d2d6c3_idx'),
        ),
    ]
