# Generated by Django 5.0.14 on 2026-09-21 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interoperability', '0001_initial'),
        ('patients', '0002_patient_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('system_type', models.CharField(choices=[('EHR_EMR', 'Electronic Health Record (Epic, Cerner, etc.)'), ('HIE', 'Health Information Exchange'), ('LAB_SYSTEM', 'Laboratory Information System (LIS)'), ('IMAGING_PACS', 'Radiology / PACS'), ('PUBLIC_HEALTH', 'Public Health Agency / CDC'), ('RESEARCH_REGISTRY', 'Research / Clinical Trial Registry')], default='EHR_EMR', max_length=50)),
                ('organization_oid', models.CharField(blank=True, help_text='HL7 OID (e.g. 2.16.840.1.113883...)', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('technical_contact', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'External Healthcare System',
                'verbose_name_plural': 'External Healthcare Systems',
                'db_table': 'interop_external_systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FHIRExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed Successfully'), ('PARTIAL_SUCCESS', 'Completed with Partial Failures'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('exported_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FHIR Export Job',
                'verbose_name_plural': 'FHIR Export Jobs',
                'db_table': 'interop_export_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending / Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed Successfully'), ('PARTIAL_SUCCESS', 'Completed with Partial Failures'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('resources_requested', models.JSONField(default=list)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('imported_records', models.PositiveIntegerField(default=0)),
                ('conflicts_generated', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('error_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FHIR Import Job',
                'verbose_name_plural': 'FHIR Import Jobs',
                'db_table': 'interop_import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRMappingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(db_index=True, default='1.0.0', max_length=30)),
                ('mapping_rules', models.JSONField(default=dict, help_text='Declarative JSON mapping rules.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('change_summary', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FHIR Mapping Version',
                'verbose_name_plural': 'FHIR Mapping Versions',
                'db_table': 'interop_mapping_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRResourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('version_id', models.CharField(blank=True, max_length=50)),
                ('payload_sha256', models.CharField(db_index=True, max_length=64)),
                ('raw_payload', models.JSONField(help_text='Exact raw external FHIR JSON representation.')),
                ('normalized_entity_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('normalized_entity_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_valid', models.BooleanField(db_index=True, default=True)),
                ('validation_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FHIR Resource Record',
                'verbose_name_plural': 'FHIR Resource Records',
                'db_table': 'interop_resource_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FHIRValidationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('resource_type', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('FATAL', 'Fatal (Rejected)'), ('ERROR', 'Error (Conflict Created)'), ('WARNING', 'Warning (Accepted with Caution)'), ('INFO', 'Informational')], db_index=True, default='ERROR', max_length=20)),
                ('rule_code', models.CharField(db_index=True, max_length=100)),
                ('error_message', models.TextField()),
                ('field_path', models.CharField(blank=True, max_length=255)),
                ('observed_value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'FHIR Validation Result',
                'verbose_name_plural': 'FHIR Validation Results',
                'db_table': 'interop_validation_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('integration.created', 'Integration Created'), ('integration.modified', 'Integration Modified'), ('integration.disabled', 'Integration Disabled'), ('import.started', 'Import Started'), ('import.completed', 'Import Completed'), ('import.failed', 'Import Failed'), ('resource.viewed', 'Resource Viewed'), ('mapping.modified', 'Mapping Modified'), ('patient_match.confirmed', 'Patient Match Confirmed'), ('patient_match.rejected', 'Patient Match Rejected'), ('export.initiated', 'Export Initiated'), ('export.completed', 'Export Completed'), ('export.rejected', 'Export Rejected'), ('terminology.changed', 'Terminology Mapping Changed'), ('reconciliation.decision', 'Reconciliation Decision Made')], db_index=True, max_length=50)),
                ('resource', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(default='HealthNova_FHIR_Hub', max_length=255)),
                ('result', models.CharField(db_index=True, default='SUCCESS', max_length=50)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Integration Audit Event',
                'verbose_name_plural': 'Integration Audit Events',
                'db_table': 'interop_audit_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True if this record has been soft-deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted (UTC).', null=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('base_url', models.URLField(help_text='FHIR R4 base URL (e.g. https://ehr.hospital.org/fhir/r4).', max_length=500)),
                ('fhir_version', models.CharField(default='4.0.1', max_length=20)),
                ('auth_type', models.CharField(choices=[('NONE', 'No Authentication (Sandbox)'), ('API_KEY', 'API Key / Header Token'), ('BEARER', 'Bearer JWT Token'), ('SMART_ON_FHIR', 'SMART on FHIR (OAuth2)'), ('MUTUAL_TLS', 'Mutual TLS (mTLS)')], default='BEARER', max_length=30)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Sanitized credentials (client_id, tokens).')),
                ('trust_level', models.CharField(choices=[('UNTRUSTED', 'Untrusted / Sandbox'), ('REVIEWED', 'Reviewed Partner System'), ('APPROVED_RESTRICTED', 'Approved (Read Only / Restricted)'), ('AUTHORITATIVE_PARTNER', 'Authoritative Clinical Partner (EHR/HIE)')], db_index=True, default='REVIEWED', max_length=30)),
                ('health_status', models.CharField(choices=[('CONNECTED', 'Connected (Verified)'), ('DEGRADED', 'Degraded (High Latency / Partial Failures)'), ('OFFLINE', 'Offline (Unreachable)'), ('AUTHENTICATION_FAILED', 'Authentication Failed'), ('VALIDATION_FAILED', 'Validation Failed'), ('CONFIGURATION_REQUIRED', 'Configuration Required'), ('NOT_CONFIGURED', 'Not Configured'), ('UNKNOWN', 'Unknown (Pending Verification)')], db_index=True, default='NOT_CONFIGURED', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allowed_direction', models.CharField(choices=[('INBOUND_IMPORT', 'Inbound Import (External -> HealthNova)'), ('OUTBOUND_EXPORT', 'Outbound Export (HealthNova -> External)'), ('BI_DIRECTIONAL', 'Bi-directional Synchronization')], default='BI_DIRECTIONAL', max_length=30)),
                ('sync_schedule_cron', models.CharField(blank=True, default='0 */6 * * *', max_length=50)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120)),
                ('timeout_seconds', models.PositiveIntegerField(default=15)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('health_details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Integration Connection',
                'verbose_name_plural': 'Integration Connections',
                'db_table': 'interop_connections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatientIdentityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('external_patient_id', models.CharField(db_index=True, max_length=255)),
                ('external_mrn', models.CharField(blank=True, db_index=True, max_length=100)),
                ('link_status', models.CharField(choices=[('CONFIRMED', 'Confirmed Match'), ('PROBABLE', 'Probable Match (Requires Review)'), ('REJECTED', 'Rejected Match (Distinct Patient)'), ('MERGED', 'Merged Identity')], db_index=True, default='CONFIRMED', max_length=30)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=1.0, max_digits=5)),
                ('matched_criteria', models.JSONField(default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Patient Identity Link',
                'verbose_name_plural': 'Patient Identity Links',
                'db_table': 'interop_patient_identity_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminologyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('source_system', models.CharField(db_index=True, max_length=255)),
                ('source_code', models.CharField(db_index=True, max_length=100)),
                ('source_display', models.CharField(blank=True, max_length=255)),
                ('target_system', models.CharField(choices=[('LOINC', 'Logical Observation Identifiers Names and Codes (LOINC)'), ('SNOMED_CT', 'SNOMED Clinical Terms'), ('ICD10', 'ICD-10-CM'), ('UCUM', 'Unified Code for Units of Measure (UCUM)'), ('RXNORM', 'RxNorm')], db_index=True, default='LOINC', max_length=50)),
                ('target_code', models.CharField(db_index=True, max_length=100)),
                ('target_display', models.CharField(max_length=255)),
                ('internal_field', models.CharField(blank=True, help_text='Mapped ClinicalRecord field (e.g. systolic_bp).', max_length=100)),
                ('is_verified', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Terminology Mapping',
                'verbose_name_plural': 'Terminology Mappings',
                'db_table': 'interop_terminology_mappings',
                'ordering': ['source_code'],
            },
        ),
        migrations.RemoveField(
            model_name='fhirauditlog',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='fhirauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fhirsyncjob',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='fhirsyncjob',
            name='triggered_by',
        ),
        migrations.RemoveIndex(
            model_name='fhirmappingconflict',
            name='fhir_mappin_existin_4d5e07_idx',
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fhir_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='discrepancy_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='existing_entity_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='existing_entity_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='incoming_payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('OVERWRITE_EXISTING', 'Overwrite Authoritative Internal Record'), ('MERGE_RECORDS', 'Merge Non-Conflicting Attributes'), ('CREATE_NEW_RECORD', 'Create Disjoint Internal Record'), ('REJECT_INCOMING', 'Reject Incoming Payload Without Modification')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='resource_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='actor_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='entity_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='entity_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='external_resource_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='fhir_resource_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='payload_sha256',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='raw_payload_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fhirexportjob',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fhir_exports', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='fhirexportjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_fhir_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fhirimportjob',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_fhir_imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='sync_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_records', to='interoperability.fhirimportjob'),
        ),
        migrations.AddField(
            model_name='fhirmappingversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fhirvalidationresult',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='interoperability.fhirimportjob'),
        ),
        migrations.AddField(
            model_name='integrationauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interop_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='external_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='interoperability.externalsystem'),
        ),
        migrations.AddField(
            model_name='integrationauditevent',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='interoperability.integrationconnection'),
        ),
        migrations.AddField(
            model_name='fhirresourcerecord',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_records', to='interoperability.integrationconnection'),
        ),
        migrations.AddField(
            model_name='fhirimportjob',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to='interoperability.integrationconnection'),
        ),
        migrations.AddField(
            model_name='fhirexportjob',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='interoperability.integrationconnection'),
        ),
        migrations.AlterField(
            model_name='fhirmappingconflict',
            name='external_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='interoperability.integrationconnection'),
        ),
        migrations.AlterField(
            model_name='fhirprovenancerecord',
            name='external_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_records', to='interoperability.integrationconnection'),
        ),
        migrations.AddField(
            model_name='patientidentitylink',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_links', to='interoperability.integrationconnection'),
        ),
        migrations.AddField(
            model_name='patientidentitylink',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identity_links', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientidentitylink',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terminologymapping',
            name='connection',
            field=models.ForeignKey(blank=True, help_text='Specific to this connection if not a global mapping.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminology_mappings', to='interoperability.integrationconnection'),
        ),
        migrations.AddField(
            model_name='terminologymapping',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FHIRAuditLog',
        ),
        migrations.DeleteModel(
            name='FHIRSyncJob',
        ),
        migrations.AlterUniqueTogether(
            name='fhirmappingversion',
            unique_together={('resource_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='integrationauditevent',
            index=models.Index(fields=['action', 'timestamp'], name='interop_aud_action_dfddc1_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationauditevent',
            index=models.Index(fields=['correlation_id'], name='interop_aud_correla_ea913d_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationauditevent',
            index=models.Index(fields=['resource', 'result'], name='interop_aud_resourc_e156a2_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcerecord',
            index=models.Index(fields=['resource_type', 'external_id'], name='interop_res_resourc_4fc6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcerecord',
            index=models.Index(fields=['payload_sha256'], name='interop_res_payload_66286c_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirresourcerecord',
            index=models.Index(fields=['normalized_entity_type', 'normalized_entity_id'], name='interop_res_normali_1a2eee_idx'),
        ),
        migrations.DeleteModel(
            name='FHIREndpoint',
        ),
        migrations.AlterUniqueTogether(
            name='patientidentitylink',
            unique_together={('connection', 'external_patient_id')},
        ),
        migrations.AlterUniqueTogether(
            name='terminologymapping',
            unique_together={('source_system', 'source_code', 'target_system')},
        ),
    ]
