# Generated by Django 5.0.14 on 2026-09-13 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_user'),
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guideline_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('organization', models.CharField(max_length=256)),
                ('section', models.CharField(max_length=256)),
                ('recommendation', models.TextField()),
                ('evidence_level', models.CharField(max_length=128)),
                ('doi_or_url', models.URLField(blank=True, max_length=512, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['guideline_id'],
            },
        ),
        migrations.CreateModel(
            name='ModelDriftRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=128)),
                ('model_version', models.CharField(max_length=32)),
                ('feature_name', models.CharField(db_index=True, max_length=64)),
                ('psi_score', models.FloatField(help_text='Population Stability Index (<0.1 stable, >0.25 severe)')),
                ('ks_statistic', models.FloatField(default=0.0)),
                ('p_value', models.FloatField(default=1.0)),
                ('is_drift_detected', models.BooleanField(default=False)),
                ('drift_alert_triggered', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'model_drift_records',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('operation_type', models.CharField(default='FULL_ORCHESTRATION', max_length=64)),
                ('input_query', models.TextField(blank=True, default='')),
                ('tools_invoked', models.JSONField(default=list, help_text='List of tools called and their latencies')),
                ('safety_status', models.CharField(choices=[('PASSED', 'Passed Safety Policies'), ('FLAGGED', 'Safety Alert Flagged'), ('SUPPRESSED', 'Output Suppressed by Guardrail')], default='PASSED', max_length=20)),
                ('guardrail_flags', models.JSONField(default=list)),
                ('requires_human_review', models.BooleanField(db_index=True, default=False)),
                ('human_decision', models.CharField(blank=True, choices=[('APPROVED', 'Clinician Approved Recommendation'), ('MODIFIED', 'Clinician Modified Plan'), ('OVERRIDDEN', 'Clinician Overrode AI Recommendation'), ('REJECTED', 'Clinician Rejected Recommendation')], max_length=20, null=True)),
                ('human_rationale', models.TextField(blank=True, default='')),
                ('human_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_ai_interactions', to=settings.AUTH_USER_MODEL)),
                ('human_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_interactions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'AI Orchestration Interaction',
                'verbose_name_plural': 'AI Orchestration Interactions',
                'db_table': 'ai_interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalRuleEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('NORMAL', 'Normal'), ('MONITOR', 'Routine Monitoring'), ('URGENT_EVALUATION', 'Urgent Clinical Evaluation'), ('CRITICAL_EMERGENCY', 'Critical Emergency')], default='NORMAL', max_length=32)),
                ('trigger_criteria', models.TextField()),
                ('recommended_action', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_evaluations', to='patients.patient')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deterministic_rules', to='predictions.prediction')),
            ],
            options={
                'db_table': 'clinical_rule_evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
