# Generated by Django 5.0.14 on 2026-09-15 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(choices=[('engineering', 'Engineering'), ('agent_coordination', 'Agent Coordination'), ('project_knowledge', 'Project Knowledge'), ('ai_evaluations', 'AI Evaluations'), ('clinical_guidelines', 'Clinical Guidelines')], db_index=True, max_length=32)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.JSONField(default=dict)),
                ('provenance', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Memory Record',
                'verbose_name_plural': 'Agent Memory Records',
                'db_table': 'agent_memory_records',
                'ordering': ['-created_at'],
                'unique_together': {('namespace', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=64)),
                ('agent_type', models.CharField(db_index=True, max_length=64)),
                ('task_type', models.CharField(db_index=True, max_length=64)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('WAITING_FOR_APPROVAL', 'Waiting for Approval'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('input_reference', models.JSONField(blank=True, default=dict)),
                ('output_reference', models.JSONField(blank=True, default=dict)),
                ('approval_required', models.BooleanField(db_index=True, default=False)),
                ('approval_status', models.CharField(choices=[('NONE', 'Not Required'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ruflo Agent Task',
                'verbose_name_plural': 'Ruflo Agent Tasks',
                'db_table': 'agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAgentTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_run_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('workflow_id', models.CharField(db_index=True, max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(default='SYSTEM', max_length=32)),
                ('agent_name', models.CharField(db_index=True, max_length=64)),
                ('agent_version', models.CharField(default='3.42.0', max_length=32)),
                ('tool_calls', models.JSONField(default=list, help_text='List of tools executed in this trace step')),
                ('input_summary', models.TextField(blank=True, default='')),
                ('output_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='COMPLETED', max_length=32)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('approval_state', models.CharField(default='NOT_REQUIRED', max_length=32)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_traces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent Trace',
                'verbose_name_plural': 'AI Agent Traces',
                'db_table': 'ai_agent_traces',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='AIApprovalGate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CLINICAL_RECOMMENDATION', 'Clinical Recommendation'), ('MODEL_PROMOTION', 'Model Promotion'), ('RETRAINING_TRIGGER', 'Retraining Trigger')], max_length=32)),
                ('workflow_id', models.CharField(db_index=True, max_length=64)),
                ('requested_by_agent', models.CharField(max_length=64)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('justification', models.TextField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('PENDING', 'Pending Decision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=16)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_gates', to='ai_orchestrator.agenttask')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ai_gates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Approval Gate',
                'verbose_name_plural': 'AI Approval Gates',
                'db_table': 'ai_approval_gates',
                'ordering': ['-created_at'],
            },
        ),
    ]
