# Generated by Django 5.0.14 on 2026-09-17 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0003_agentdefinition_aimodelconfig_knowledgesource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClineMCPServerRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('endpoint', models.CharField(max_length=512)),
                ('transport', models.CharField(default='HTTP_SSE', max_length=32)),
                ('owner', models.CharField(default='HEALTHNOVA_INFRA', max_length=128)),
                ('trust_level', models.CharField(choices=[('SANDBOXED_LOCAL', 'Sandboxed Local Network'), ('VERIFIED_CONTAINER', 'Verified Container Subnet'), ('RESTRICTED_ADMIN', 'Restricted Admin Only')], default='SANDBOXED_LOCAL', max_length=32)),
                ('data_classification', models.CharField(choices=[('PUBLIC', 'Public Non-Clinical Data'), ('INTERNAL', 'Internal Hospital Operations'), ('SENSITIVE', 'Sensitive Business Data'), ('PHI', 'PHI Capable (Restricted Authorization Required)'), ('CRITICAL', 'Critical Infrastructure')], default='INTERNAL', max_length=32)),
                ('allowed_roles', models.JSONField(default=list)),
                ('allowed_tools', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=False, help_text='Default is FALSE (Default-Deny policy)')),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cline MCP Server Registry',
                'verbose_name_plural': 'Cline MCP Server Registries',
                'db_table': 'cline_mcp_server_registry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClineToolDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.TextField()),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical (Default Deny)')], default='LOW', max_length=16)),
                ('allowed_roles', models.JSONField(default=list)),
                ('allowed_environments', models.JSONField(default=list)),
                ('requires_approval', models.BooleanField(default=False)),
                ('data_classification', models.CharField(default='INTERNAL', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cline Tool Definition',
                'verbose_name_plural': 'Cline Tool Definitions',
                'db_table': 'cline_tool_definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClineAgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(db_index=True, default='DOCTOR', max_length=32)),
                ('agent_type', models.CharField(db_index=True, default='CLINICAL_KNOWLEDGE_ASSISTANT', max_length=64)),
                ('purpose', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('WAITING_FOR_APPROVAL', 'Waiting for Approval'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated')], db_index=True, default='IDLE', max_length=32)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('environment', models.CharField(choices=[('DEVELOPMENT', 'Development Sandbox'), ('STAGING', 'Staging Environment'), ('PRODUCTION', 'Production Guarded')], default='DEVELOPMENT', max_length=32)),
                ('approval_policy', models.CharField(choices=[('STRICT', 'Strict (All Medium+ require human sign-off)'), ('ELEVATED', 'Elevated (High+ require human sign-off)'), ('READ_ONLY', 'Read Only (No mutations permitted)')], default='STRICT', max_length=32)),
                ('token_budget', models.PositiveIntegerField(default=100000, help_text='Maximum tokens permitted in session')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('max_tool_calls', models.PositiveIntegerField(default=20, help_text='Maximum tool executions per session')),
                ('tool_calls_count', models.PositiveIntegerField(default=0)),
                ('cost_limit_usd', models.DecimalField(decimal_places=4, default=2.0, max_digits=8)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cline_agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cline Agent Session',
                'verbose_name_plural': 'Cline Agent Sessions',
                'db_table': 'cline_agent_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClineAgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(db_index=True, default='QUERY_ANALYSIS', max_length=64)),
                ('prompt_hash', models.CharField(help_text='SHA-256 hash of task prompt (avoids PHI storage)', max_length=64)),
                ('prompt_summary', models.TextField(blank=True, default='', help_text='PHI-redacted summary')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('WAITING_FOR_APPROVAL', 'Waiting for Approval'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMED_OUT', 'Timed Out')], db_index=True, default='QUEUED', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('tool_calls_count', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cline_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cline_tasks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_orchestrator.clineagentsession')),
            ],
            options={
                'verbose_name': 'Cline Agent Task',
                'verbose_name_plural': 'Cline Agent Tasks',
                'db_table': 'cline_agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClineAgentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('agent_started', 'Agent Started'), ('agent_thinking_summary', 'Agent Thinking Summary'), ('tool_requested', 'Tool Requested'), ('tool_approved', 'Tool Approved'), ('tool_denied', 'Tool Denied'), ('tool_completed', 'Tool Completed'), ('agent_message', 'Agent Message'), ('agent_warning', 'Agent Warning'), ('agent_error', 'Agent Error'), ('agent_completed', 'Agent Completed')], db_index=True, max_length=32)),
                ('tool_name', models.CharField(blank=True, default='', max_length=128)),
                ('resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('resource_id', models.CharField(blank=True, default='', max_length=128)),
                ('summary', models.TextField(help_text='Safe redacted summary (zero PHI, zero private CoT)')),
                ('approval_state', models.CharField(default='NOT_REQUIRED', max_length=32)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai_orchestrator.clineagentsession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai_orchestrator.clineagenttask')),
            ],
            options={
                'verbose_name': 'Cline Agent Event',
                'verbose_name_plural': 'Cline Agent Events',
                'db_table': 'cline_agent_events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClineAgentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_action', models.CharField(max_length=128)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='MEDIUM', max_length=16)),
                ('details', models.JSONField(default=dict, help_text='Redacted parameter payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Decision'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cline_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cline_approvals', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='ai_orchestrator.clineagenttask')),
            ],
            options={
                'verbose_name': 'Cline Agent Approval',
                'verbose_name_plural': 'Cline Agent Approvals',
                'db_table': 'cline_agent_approvals',
                'ordering': ['-timestamp'],
            },
        ),
    ]
