# Generated by Django 5.0.14 on 2026-09-17 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0004_clinemcpserverregistry_clinetooldefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('dimension', models.IntegerField(default=768)),
                ('distance_metric', models.CharField(default='COSINE', max_length=32)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embedding Registry',
                'verbose_name_plural': 'Embedding Registries',
                'db_table': 'embedding_registry',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='LLMModelRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('tag', models.CharField(db_index=True, max_length=128, unique=True)),
                ('provider', models.CharField(db_index=True, default='OLLAMA', max_length=64)),
                ('runtime', models.CharField(default='LOCAL_CONTAINER', max_length=64)),
                ('context_length', models.IntegerField(default=4096)),
                ('capabilities', models.JSONField(default=list, help_text="e.g. ['chat', 'structured_output', 'tool_calling', 'embeddings']")),
                ('license', models.CharField(default='Open Source', max_length=128)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered in Daemon'), ('EVALUATING', 'Under Evaluation Benchmarks'), ('APPROVED', 'Approved by Clinical Informaticist'), ('ACTIVE', 'Active in Routing Pipeline'), ('DEPRECATED', 'Deprecated'), ('RETIRED', 'Retired')], db_index=True, default='DISCOVERED', max_length=32)),
                ('environment', models.CharField(default='PRODUCTION', max_length=64)),
                ('approved_roles', models.JSONField(default=list, help_text='Roles authorized to invoke this model')),
                ('data_classification', models.CharField(default='RESTRICTED_PHI', max_length=64)),
                ('parameters_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Model Registry',
                'verbose_name_plural': 'LLM Model Registries',
                'db_table': 'llm_model_registry',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='DOCTOR', max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('provider', models.CharField(default='OLLAMA', max_length=64)),
                ('purpose', models.CharField(default='CLINICAL_DECISION_SUPPORT', max_length=128)),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Session',
                'verbose_name_plural': 'AI Sessions',
                'db_table': 'ai_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(db_index=True, max_length=128)),
                ('provider', models.CharField(default='OLLAMA', max_length=64)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('status', models.CharField(default='COMPLETED', max_length=32)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='ai_orchestrator.aisession')),
            ],
            options={
                'verbose_name': 'AI Request Audit',
                'verbose_name_plural': 'AI Request Audits',
                'db_table': 'ai_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
