# Generated by Django 5.0.14 on 2026-09-23 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0005_embeddingregistry_llmmodelregistry_aisession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedDecisionProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='laya-mlx', max_length=64, unique=True)),
                ('display_name', models.CharField(default='Laya-MLX Native Runtime', max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
                ('runtime_mode', models.CharField(default='auto', max_length=32)),
                ('service_url', models.CharField(blank=True, default='', max_length=255)),
                ('platform_supported', models.BooleanField(default=False)),
                ('health_status', models.CharField(default='SUPPORTED', max_length=32)),
                ('capabilities_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Typed Decision Provider',
                'verbose_name_plural': 'Typed Decision Providers',
                'db_table': 'typed_decision_providers',
            },
        ),
        migrations.CreateModel(
            name='TypedDecisionAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64)),
                ('actor_role', models.CharField(default='SYSTEM', max_length=64)),
                ('target_identifier', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typed Decision Audit Event',
                'verbose_name_plural': 'Typed Decision Audit Events',
                'db_table': 'typed_decision_audit_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypedDecisionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_identifier', models.CharField(default='convaiinnovations/laya', max_length=128)),
                ('model_revision', models.CharField(default='573e5b62696ba441230cd6be71d593331b5d23af', max_length=64)),
                ('model_checksum', models.CharField(default='sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', max_length=128)),
                ('architecture', models.CharField(default='ModernBERT-DecisionModel', max_length=64)),
                ('parameter_count', models.CharField(default='149M', max_length=32)),
                ('context_limit', models.IntegerField(default=512)),
                ('dtype', models.CharField(default='float16', max_length=32)),
                ('license', models.CharField(default='Apache-2.0', max_length=64)),
                ('provenance', models.CharField(default='https://github.com/mizorewww/laya-mlx', max_length=255)),
                ('validation_status', models.CharField(default='VERIFIED', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_orchestrator.typeddecisionprovider')),
            ],
            options={
                'verbose_name': 'Typed Decision Model',
                'verbose_name_plural': 'Typed Decision Models',
                'db_table': 'typed_decision_models',
            },
        ),
        migrations.CreateModel(
            name='TypedDecisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(default='DOCTOR', max_length=64)),
                ('correlation_id', models.CharField(db_index=True, max_length=64)),
                ('context_hash', models.CharField(help_text='SHA-256 of minimized context', max_length=64)),
                ('had_phi_redaction', models.BooleanField(default=False)),
                ('decision_type', models.CharField(default='CHOICE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ai_orchestrator.typeddecisionprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_decision_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typed Decision Request',
                'verbose_name_plural': 'Typed Decision Requests',
                'db_table': 'typed_decision_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypedDecisionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_value', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('probabilities', models.JSONField(blank=True, default=dict)),
                ('uncertainty_status', models.CharField(choices=[('SUPPORTED', 'Supported by strong confidence'), ('PARTIALLY_SUPPORTED', 'Moderate confidence'), ('INSUFFICIENT_DATA', 'Context lacks critical clinical attributes'), ('CONFLICTING_DATA', 'Context presents contradictory signals'), ('LOW_CONFIDENCE', 'Below minimum confidence threshold'), ('REQUIRES_CLINICIAN_REVIEW', 'High clinical impact requires review'), ('PROVIDER_UNAVAILABLE', 'Provider offline or unsupported')], default='SUPPORTED', max_length=32)),
                ('requires_human_review', models.BooleanField(db_index=True, default=False)),
                ('clinician_review_status', models.CharField(default='PENDING', max_length=32)),
                ('clinician_action', models.CharField(blank=True, default='', max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ai_orchestrator.typeddecisionrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_typed_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typed Decision Result',
                'verbose_name_plural': 'Typed Decision Results',
                'db_table': 'typed_decision_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypedDecisionSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('version', models.CharField(default='1.0.0', max_length=32)),
                ('decision_type', models.CharField(choices=[('CHOICE', 'Categorical Choice'), ('SCORE', 'Numerical Urgency Score'), ('BOOLEAN', 'Boolean / Noul Flag')], default='CHOICE', max_length=32)),
                ('instructions', models.TextField(help_text='Task guidance for the decision engine')),
                ('allowed_options', models.JSONField(default=list, help_text='List of string choices or score criteria')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Safety and range validation constraints')),
                ('clinical_context', models.CharField(default='TRIAGE_WORKFLOW', help_text='Clinical operational domain', max_length=128)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Schema'), ('VALIDATION', 'Pending Permutation & Safety Validation'), ('APPROVED', 'Approved by Clinical Informaticist'), ('ACTIVE', 'Active in Clinical Workflows'), ('SUSPENDED', 'Temporarily Suspended'), ('RETIRED', 'Retired Schema')], db_index=True, default='DRAFT', max_length=32)),
                ('robustness_status', models.CharField(default='NOT_EVALUATED', max_length=32)),
                ('robustness_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_decision_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typed Decision Schema',
                'verbose_name_plural': 'Typed Decision Schemas',
                'db_table': 'typed_decision_schemas',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='typeddecisionrequest',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='ai_orchestrator.typeddecisionschema'),
        ),
        migrations.CreateModel(
            name='TypedDecisionEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sample_size', models.IntegerField(default=0)),
                ('robustness_score', models.FloatField(blank=True, null=True)),
                ('calibration_error', models.FloatField(blank=True, null=True)),
                ('average_latency_ms', models.FloatField(default=0.0)),
                ('override_rate', models.FloatField(default=0.0)),
                ('passed_robustness', models.BooleanField(default=True)),
                ('evaluation_details', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='ai_orchestrator.typeddecisionmodel')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='ai_orchestrator.typeddecisionschema')),
            ],
            options={
                'verbose_name': 'Typed Decision Evaluation',
                'verbose_name_plural': 'Typed Decision Evaluations',
                'db_table': 'typed_decision_evaluations',
                'ordering': ['-evaluated_at'],
            },
        ),
    ]
