# Generated by Django 5.0.14 on 2026-09-23 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_orchestrator', '0006_typeddecisionprovider_typeddecisionauditevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedDecisionLanguageEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(db_index=True, max_length=16)),
                ('language_name', models.CharField(max_length=64)),
                ('checkpoint', models.CharField(default='convaiinnovations/laya-multilingual', max_length=128)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('calibration_error', models.FloatField(blank=True, null=True)),
                ('confidence_mean', models.FloatField(blank=True, null=True)),
                ('abstention_rate', models.FloatField(blank=True, null=True)),
                ('human_override_rate', models.FloatField(blank=True, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('is_clinically_validated', models.BooleanField(default=False)),
                ('status', models.CharField(default='NOT_EVALUATED', max_length=32)),
                ('evaluation_notes', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Typed Decision Language Evaluation',
                'verbose_name_plural': 'Typed Decision Language Evaluations',
                'db_table': 'typed_decision_language_evaluations',
                'ordering': ['language_name'],
                'unique_together': {('language_code', 'checkpoint')},
            },
        ),
    ]
