# Generated by Django 5.0.14 on 2026-09-17 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coolify_resource_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('environment', models.CharField(default='PRODUCTION', max_length=50)),
                ('repository', models.CharField(default='healthnova/cdss-platform', max_length=255)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('deployment_status', models.CharField(default='IDLE', max_length=50)),
                ('last_deployment_id', models.CharField(blank=True, default='', max_length=100)),
                ('last_deployed_commit', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deployment Application',
                'verbose_name_plural': 'Deployment Applications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coolify_server_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('environment', models.CharField(default='PRODUCTION', max_length=50)),
                ('status', models.CharField(default='HEALTHY', max_length=50)),
                ('region', models.CharField(default='us-east-2', max_length=50)),
                ('provider', models.CharField(default='Dedicated VM', max_length=100)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Infrastructure Server',
                'verbose_name_plural': 'Infrastructure Servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coolify_deployment_id', models.CharField(db_index=True, max_length=100)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('UNKNOWN', 'Unknown')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('trigger', models.CharField(default='MANUAL', max_length=50)),
                ('environment', models.CharField(default='PRODUCTION', max_length=50)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_deployments', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='infrastructure.deploymentapplication')),
            ],
            options={
                'verbose_name': 'Deployment Record',
                'verbose_name_plural': 'Deployment Records',
                'ordering': ['-started_at'],
            },
        ),
    ]
