# Generated by Django 5.0.14 on 2026-09-18 15:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_deploymentrecord_versioning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('DATABASE_PITR', 'Neon Continuous WAL / Branch Snapshot'), ('DATABASE_LOGICAL', 'Encrypted Logical pg_dump'), ('CONFIGURATION', 'Platform / Nginx / Coolify Config'), ('ML_METADATA', 'Model Registry & Dataset Lineage Manifest'), ('FULL_SNAPSHOT', 'Unified Clinical Platform Snapshot')], default='DATABASE_LOGICAL', max_length=50)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('storage_provider', models.CharField(choices=[('NEON_POSTGRES', 'Neon PostgreSQL (Continuous WAL)'), ('AWS_S3_KMS', 'AWS S3 (KMS Encrypted Bucket)'), ('LOCAL_SECURE', 'Isolated Encrypted Volume')], default='NEON_POSTGRES', max_length=50)),
                ('storage_location', models.CharField(blank=True, default='', max_length=500)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA-256 checksum of the backup archive.', max_length=64)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM / AWS-KMS', max_length=50)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('VALIDATED', 'Validated & Integrity Verified'), ('FAILED', 'Validation Failed')], db_index=True, default='PENDING', max_length=20)),
                ('validation_details', models.JSONField(blank=True, default=dict)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisasterRecoveryDrill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drill_name', models.CharField(max_length=200)),
                ('recovery_type', models.CharField(choices=[('DATABASE', 'Neon Database Point-In-Time Restoration'), ('REDIS', 'Redis Broker & Cache Reconstruction'), ('CELERY', 'Celery Task Queue & Worker Recovery'), ('APPLICATION', 'Application Container & Daphne ASGI Restart'), ('DOCKER', 'Docker Image Digest & Registry Recovery'), ('COOLIFY', 'Coolify Platform & Orchestration Recovery'), ('REGISTRY', 'Container Registry Rollback'), ('ML_MODEL', 'ML Model Registry & Checksum Verification'), ('SEARCH', 'Meilisearch Index Rebuild from Neon Source'), ('AI', 'AI Gateway & Safe Degraded Fallback'), ('CREDENTIAL', 'Credential Compromise & Secret Rotation'), ('COMPLETE_ENV', 'Complete Environment Disaster Recovery')], default='DATABASE', max_length=50)),
                ('target_service', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('DETECTED', 'Detected'), ('ACKNOWLEDGED', 'Acknowledged'), ('CONTAINED', 'Contained'), ('RECOVERING', 'Recovering'), ('VERIFIED', 'Verified'), ('RESOLVED', 'Resolved'), ('POSTMORTEM', 'Postmortem')], db_index=True, default='DETECTED', max_length=20)),
                ('verification_status', models.CharField(choices=[('NOT_TESTED', 'Not Tested'), ('CONFIGURED', 'Configured'), ('TESTED', 'Tested'), ('VERIFIED', 'Verified'), ('FAILED', 'Verification Failed')], db_index=True, default='NOT_TESTED', max_length=20)),
                ('environment', models.CharField(default='DR_SIMULATION', max_length=50)),
                ('checklist_results', models.JSONField(blank=True, default=dict, help_text='14-item verification checklist state and probe results.')),
                ('recovery_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_drills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disaster Recovery Drill',
                'verbose_name_plural': 'Disaster Recovery Drills',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryTargetConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_configured', models.BooleanField(default=False, help_text='Flag indicating whether RPO/RTO targets have been formally approved.')),
                ('approved_rpo_minutes', models.PositiveIntegerField(blank=True, help_text='Approved Recovery Point Objective in minutes (maximum acceptable data loss window).', null=True)),
                ('approved_rto_minutes', models.PositiveIntegerField(blank=True, help_text='Approved Recovery Time Objective in minutes (maximum acceptable recovery duration).', null=True)),
                ('backup_cadence', models.CharField(choices=[('NOT_DEFINED', 'Not yet defined'), ('CONTINUOUS_WAL', 'Continuous WAL (Neon Safekeepers)'), ('HOURLY', 'Hourly Incremental'), ('DAILY_OFFSITE', 'Daily Encrypted S3 Export')], default='NOT_DEFINED', max_length=50)),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='Approved retention window in days.', null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_framework', models.CharField(default='HIPAA Security Rule / 21 CFR Part 11', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dr_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Target Configuration',
                'verbose_name_plural': 'Recovery Target Configurations',
            },
        ),
        migrations.CreateModel(
            name='RollbackRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rollback_type', models.CharField(choices=[('APPLICATION', 'Full Application Stack'), ('FRONTEND', 'Next.js Frontend Container'), ('BACKEND', 'Django ASGI Backend'), ('WORKER', 'Celery Async Worker'), ('MODEL', 'ML Model Artifact'), ('CONFIGURATION', 'Infrastructure Configuration')], default='APPLICATION', max_length=30)),
                ('service_name', models.CharField(max_length=100)),
                ('current_commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('target_commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('current_model_version', models.CharField(blank=True, default='', max_length=50)),
                ('target_model_version', models.CharField(blank=True, default='', max_length=50)),
                ('compatibility_verified', models.BooleanField(default=False, help_text='True if target version schema/API was explicitly checked for backward compatibility.')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='STARTED', max_length=20)),
                ('reason', models.TextField()),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_rollbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rollback Record',
                'verbose_name_plural': 'Rollback Records',
                'ordering': ['-started_at'],
            },
        ),
    ]
