# Generated by Django 5.0.14 on 2026-09-18 15:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_backuprecord_disasterrecoverydrill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureDriftRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(db_index=True, default='production', max_length=50)),
                ('is_drifted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('IN_SYNC', 'In Sync'), ('DRIFT_DETECTED', 'Drift Detected'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='IN_SYNC', max_length=30)),
                ('exit_code', models.IntegerField(default=0)),
                ('drift_summary', models.TextField(blank=True)),
                ('remediation_plan', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Infrastructure Drift Record',
                'verbose_name_plural': 'Infrastructure Drift Records',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructurePolicyCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(default='OPA_REGO', max_length=50)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('WARNING', 'Warning')], default='PASSED', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Infrastructure Policy Check',
                'verbose_name_plural': 'Infrastructure Policy Checks',
                'ordering': ['-evaluated_at'],
            },
        ),
        migrations.CreateModel(
            name='IaCPlanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(db_index=True, default='production', max_length=50)),
                ('tool', models.CharField(default='OpenTofu', max_length=50)),
                ('plan_output', models.TextField()),
                ('resources_to_add', models.IntegerField(default=0)),
                ('resources_to_change', models.IntegerField(default=0)),
                ('resources_to_destroy', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('APPLIED', 'Applied'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('requires_human_approval', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_iac_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IaC Plan Record',
                'verbose_name_plural': 'IaC Plan Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
