# Generated by Django 5.0.14 on 2026-09-13 18:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_user'),
        ('predictions', '0002_clinicalreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(default='Cardiology Clinic', max_length=100)),
                ('scheduled_time', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=30)),
                ('location_or_link', models.CharField(default='Suite 402 - Heart & Vascular Center', max_length=255)),
                ('reason_for_visit', models.CharField(default='Cardiovascular Follow-up', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_appointments',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('AI_DECISION_SUPPORT', 'AI Clinical Decision Support'), ('DATA_SHARING', 'Clinical Data Exchange'), ('SMS_NOTIFICATIONS', 'SMS & Real-time Alerts'), ('TELEHEALTH', 'Telehealth Audio/Video Encounters')], db_index=True, max_length=50)),
                ('is_granted', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_consent_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='General Clinical Inquiry', max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Active Discussion'), ('RESOLVED', 'Resolved'), ('ARCHIVED', 'Archived')], default='OPEN', max_length=20)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinician_conversations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('read_by_patient', models.BooleanField(default=False)),
                ('read_by_clinician', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patient_portal.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('chest_pain_type', models.CharField(default='ASYMPTOMATIC', max_length=50)),
                ('resting_bp', models.IntegerField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('fasting_blood_sugar', models.CharField(default='< 120 mg/dl', max_length=20)),
                ('resting_ecg', models.CharField(default='Normal', max_length=50)),
                ('max_heart_rate', models.IntegerField(blank=True, null=True)),
                ('exercise_angina', models.CharField(default='No', max_length=20)),
                ('st_depression', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing Assessment'), ('PROCESSING', 'Inference in Progress'), ('COMPLETED', 'Completed'), ('CLINICAL_REVIEW_REQUIRED', 'Clinical Review Required'), ('FAILED', 'Failed')], db_index=True, default='PREPARING', max_length=40)),
                ('patient_notes', models.TextField(blank=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assessments', to='patients.patient')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_assessments', to='predictions.prediction')),
            ],
            options={
                'db_table': 'user_risk_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('LOG_VITALS', 'Log Daily Vitals'), ('QUESTIONNAIRE', 'Health Questionnaire'), ('MEDICATION_CONFIRM', 'Medication Confirmation'), ('APPOINTMENT_PREP', 'Appointment Preparation')], default='LOG_VITALS', max_length=40)),
                ('due_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_tasks', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_portal_tasks',
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='UserVitalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('source', models.CharField(choices=[('USER_ENTERED', 'Patient Self-Reported'), ('DEVICE', 'Connected Medical Device'), ('CLINICIAN', 'Clinical Staff Verified'), ('IMPORTED', 'EHR Import')], default='USER_ENTERED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vitals', to='patients.patient')),
            ],
            options={
                'db_table': 'user_vital_records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
