"use client";

import React, { useState } from "react";
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  FileCheck,
  Info,
  RefreshCw,
  ShieldCheck,
  UserCheck,
} from "lucide-react";
import apiClient from "@/services/apiClient";

interface ShapFeature {
  feature: string;
  importance: number;
  value?: string | number;
}

interface ClinicalExplanationData {
  prediction_id: string;
  model_family: string;
  risk_score: number;
  top_contributing_features: ShapFeature[];
  clinical_narrative: string;
  recommended_monitoring_interval: string;
  human_signoff_required: boolean;
}

interface Props {
  predictionId?: string;
  initialScore?: number;
  modelName?: string;
  onSignOff?: (signedExplanation: ClinicalExplanationData) => void;
}

export function ClinicalPredictionExplainer({
  predictionId,
  initialScore = 0.76,
  modelName = "Random Forest Classifier (scikit-learn)",
  onSignOff,
}: Props) {
  const [loading, setLoading] = useState<boolean>(false);
  const [explanation, setExplanation] = useState<ClinicalExplanationData | null>(null);
  const [signed, setSigned] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const fetchExplanation = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await apiClient.post<ClinicalExplanationData>(
        "/ai/providers/ollama/explain-prediction/",
        {
          prediction_id: predictionId,
          risk_score: initialScore,
          model_family: modelName,
        }
      );
      setExplanation(res.data);
      setSigned(false);
    } catch (err: any) {
      setError(err?.response?.data?.error || "Failed to generate clinical explanation.");
    } finally {
      setLoading(false);
    }
  };

  const handleSignOff = () => {
    if (!explanation) return;
    setSigned(true);
    if (onSignOff) {
      onSignOff(explanation);
    }
  };

  const getRiskColor = (score: number) => {
    if (score >= 0.75) return "text-rose-600 bg-rose-50 border-rose-200";
    if (score >= 0.4) return "text-amber-600 bg-amber-50 border-amber-200";
    return "text-emerald-600 bg-emerald-50 border-emerald-200";
  };

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-100 pb-4">
        <div>
          <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
            <Activity className="w-5 h-5 text-blue-600" />
            Classical ML + Local Ollama Risk Explainability
          </h3>
          <p className="text-xs text-slate-500 mt-1">
            Prediction generated by validated scikit-learn models. Explanation synthesized on-premises by Ollama.
          </p>
        </div>

        <button
          onClick={fetchExplanation}
          disabled={loading}
          className="inline-flex items-center gap-1.5 px-3.5 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 font-medium text-xs rounded-lg border border-blue-200 transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin text-blue-600" : ""}`} />
          {loading ? "Synthesizing..." : explanation ? "Re-synthesize" : "Explain Prediction"}
        </button>
      </div>

      {error && (
        <div className="p-3 bg-rose-50 border border-rose-200 rounded-lg text-xs text-rose-700">
          {error}
        </div>
      )}

      {/* Prediction Baseline Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="p-4 rounded-lg bg-slate-50 border border-slate-200">
          <span className="text-[11px] uppercase tracking-wider font-semibold text-slate-500">ML Model Family</span>
          <p className="text-xs font-bold text-slate-800 mt-1">{explanation?.model_family || modelName}</p>
        </div>

        <div className="p-4 rounded-lg bg-slate-50 border border-slate-200">
          <span className="text-[11px] uppercase tracking-wider font-semibold text-slate-500">Risk Probability</span>
          <div className="mt-1 flex items-center gap-2">
            <span
              className={`px-2.5 py-0.5 rounded-full text-xs font-bold border ${getRiskColor(
                explanation?.risk_score ?? initialScore
              )}`}
            >
              {Math.round((explanation?.risk_score ?? initialScore) * 100)}%
            </span>
          </div>
        </div>

        <div className="p-4 rounded-lg bg-slate-50 border border-slate-200">
          <span className="text-[11px] uppercase tracking-wider font-semibold text-slate-500">Monitoring Cadence</span>
          <p className="text-xs font-semibold text-slate-800 mt-1">
            {explanation?.recommended_monitoring_interval || "Every 2 - 4 hours"}
          </p>
        </div>
      </div>

      {explanation && (
        <div className="space-y-4">
          {/* Top SHAP Feature importances */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-600 mb-2">
              Top SHAP Feature Attributions
            </h4>
            <div className="space-y-2">
              {explanation.top_contributing_features.map((feat, idx) => {
                const pct = Math.min(100, Math.round(feat.importance * 100));
                return (
                  <div key={idx} className="space-y-1">
                    <div className="flex justify-between text-xs text-slate-700">
                      <span className="font-medium">{feat.feature}</span>
                      <span className="font-mono text-slate-500">
                        {feat.value ? `Val: ${feat.value} | ` : ""}Imp: {feat.importance.toFixed(2)}
                      </span>
                    </div>
                    <div className="h-1.5 w-full bg-slate-100 rounded-full overflow-hidden">
                      <div
                        className="h-full bg-blue-600 rounded-full"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Ollama Synthesized Clinical Narrative */}
          <div className="p-4 rounded-lg bg-blue-50/50 border border-blue-100 space-y-2">
            <div className="flex items-center gap-2 text-xs font-bold text-blue-900">
              <Info className="w-4 h-4 text-blue-600" />
              Local Ollama Clinical Synthesis
            </div>
            <p className="text-xs text-slate-700 leading-relaxed">
              {explanation.clinical_narrative}
            </p>
          </div>

          {/* Clinician Human Sign-Off Gate */}
          <div className="pt-2 flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-t border-slate-100">
            <div className="flex items-center gap-2 text-[11px] text-slate-500">
              <ShieldCheck className="w-4 h-4 text-emerald-600" />
              <span>Mandatory Clinician Sign-Off Required Prior to EHR Entry</span>
            </div>

            {signed ? (
              <div className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-lg text-xs font-semibold">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                Signed & Approved by Clinician
              </div>
            ) : (
              <button
                onClick={handleSignOff}
                className="inline-flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-medium text-xs rounded-lg transition-colors shadow-sm"
              >
                <UserCheck className="w-3.5 h-3.5" />
                Sign & Approve Explanation
              </button>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
