# Generated by Django 5.0.14 on 2026-09-17 10:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndexRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('classification', models.CharField(default='INTERNAL', max_length=32)),
                ('schema_version', models.CharField(default='1.0.0', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REBUILDING', 'Rebuilding'), ('DEGRADED', 'Degraded'), ('DISABLED', 'Disabled'), ('FAILED', 'Failed')], db_index=True, default='ACTIVE', max_length=32)),
                ('document_count', models.IntegerField(default=0)),
                ('last_reindex', models.DateTimeField(blank=True, null=True)),
                ('last_reconciliation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_index_registry',
                'ordering': ['index_uid'],
            },
        ),
        migrations.CreateModel(
            name='SearchOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=128)),
                ('action', models.CharField(default='UPSERT', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_outbox_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id_ref', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(db_index=True, max_length=64)),
                ('index_name', models.CharField(db_index=True, max_length=64)),
                ('redacted_query', models.CharField(blank=True, default='', max_length=255)),
                ('result_count', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('search_mode', models.CharField(default='meilisearch', max_length=32)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_audit_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
