# Generated by Django 5.0.14 on 2026-09-13 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('report_type', models.CharField(choices=[('RISK_ASSESSMENT', 'Patient Risk Assessment Summary'), ('DISCHARGE_SUMMARY', 'Discharge & Trend Summary'), ('CLINICAL_AUDIT', 'Clinical Department Audit'), ('MODEL_PERFORMANCE', 'ML Model Accuracy Report')], default='RISK_ASSESSMENT', max_length=50)),
                ('format', models.CharField(choices=[('PDF', 'PDF Document'), ('CSV', 'CSV Spreadsheet'), ('JSON', 'JSON Data Export')], default='PDF', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Storage location of the compiled report file.', max_length=500)),
                ('file_size_bytes', models.IntegerField(blank=True, help_text='File size in bytes.', null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Generation options and filter criteria.')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, help_text='Staff member who generated or scheduled this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient associated with this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patient')),
                ('prediction', models.ForeignKey(blank=True, help_text='Specific prediction evaluated in this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='predictions.prediction')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='reports_patient_becf25_idx'), models.Index(fields=['status', 'created_at'], name='reports_status_19e159_idx')],
            },
        ),
    ]
