"use client";

import * as React from "react";
import Link from "next/link";
import {
  FileText,
  ArrowLeft,
  ShieldCheck,
  Download,
  CheckCircle2,
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import apiClient from "@/services/apiClient";

export default function SecurityReportsPage() {
  const [reports, setReports] = React.useState<any[]>([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    apiClient
      .get("/security/reports/")
      .then((res) => {
        const data = Array.isArray(res.data) ? res.data : res.data?.results || [];
        setReports(data);
      })
      .catch((e) => console.error(e))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6 pb-12 bg-slate-50 min-h-screen text-slate-900 p-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Link href="/admin/security">
            <Button variant="ghost" size="sm" className="text-slate-500 hover:text-slate-800">
              <ArrowLeft className="w-4 h-4 mr-1" />
              Back to Overview
            </Button>
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-slate-900">Security Reports</h1>
            <p className="text-xs text-slate-500">
              Auditable security reports generated from validated findings. Requires human reviewer sign-off.
            </p>
          </div>
        </div>
      </div>

      <Card className="bg-white border-slate-200 shadow-sm">
        <CardHeader className="border-b border-slate-100">
          <CardTitle className="text-base font-semibold text-slate-900">Generated Reports ({reports.length})</CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {loading ? (
            <div className="py-12 text-center text-slate-400 text-sm">Loading security reports...</div>
          ) : reports.length === 0 ? (
            <div className="py-12 text-center text-slate-500 text-sm">No security reports have been generated.</div>
          ) : (
            <div className="divide-y divide-slate-100">
              {reports.map((r) => (
                <div key={r.id} className="p-4 flex items-center justify-between hover:bg-slate-50/60 transition-colors">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="font-semibold text-xs text-slate-900">{r.title}</span>
                      <Badge variant="outline" className="text-[10px] font-mono border-slate-200">
                        {r.report_type}
                      </Badge>
                      {r.is_approved ? (
                        <Badge className="bg-emerald-100 text-emerald-800 text-[10px]">Approved</Badge>
                      ) : (
                        <Badge className="bg-amber-100 text-amber-800 text-[10px]">Pending Review</Badge>
                      )}
                    </div>
                    <p className="text-[11px] text-slate-500">
                      Generated by {r.generated_by_name || "Admin"} • {new Date(r.created_at).toLocaleDateString()}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
