# Generated by Django 5.0.14 on 2026-09-13 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp (UTC).')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last-modification timestamp (UTC).')),
                ('name', models.CharField(help_text='Human-readable model name.', max_length=255)),
                ('model_type', models.CharField(choices=[('SVM', 'Support Vector Machine'), ('RANDOM_FOREST', 'Random Forest'), ('ADABOOST', 'AdaBoost')], db_index=True, max_length=30)),
                ('dataset_name', models.CharField(db_index=True, help_text="Name of the dataset used for training (e.g. 'pima_diabetes').", max_length=100)),
                ('version', models.CharField(help_text="Semantic version string (e.g. '1.0.0').", max_length=50)),
                ('status', models.CharField(choices=[('TRAINING', 'Training'), ('TRAINED', 'Trained'), ('EVALUATING', 'Evaluating'), ('ACTIVE', 'Active (Production)'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='TRAINING', max_length=20)),
                ('artifact_path', models.CharField(blank=True, help_text='Relative path to the joblib artifact file.', max_length=500)),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Model evaluation metrics (accuracy, F1, ROC-AUC, etc.).')),
                ('hyperparameters', models.JSONField(blank=True, default=dict, help_text='Hyperparameters used during training.')),
                ('feature_names', models.JSONField(blank=True, default=list, help_text='Ordered list of feature names expected by the model.')),
                ('training_started_at', models.DateTimeField(blank=True, null=True)),
                ('training_completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'model_type'], name='ml_models_status_a6019b_idx'), models.Index(fields=['dataset_name', 'status'], name='ml_models_dataset_1350dd_idx')],
                'unique_together': {('model_type', 'dataset_name', 'version')},
            },
        ),
    ]
