"""
Configuration and constants for the Meilisearch integration.
"""
from decouple import config

# Engine version & connection parameters
MEILISEARCH_VERSION = "1.12.0"
MEILISEARCH_HOST = config("MEILISEARCH_HOST", default="http://localhost:7700")
MEILISEARCH_MASTER_KEY = config("MEILISEARCH_MASTER_KEY", default="healthnova_meili_master_secret_key_32c")
MEILISEARCH_TIMEOUT_SECONDS = config("MEILISEARCH_TIMEOUT_SECONDS", default=5, cast=int)
MEILISEARCH_SCHEMA_VERSION = config("MEILISEARCH_SCHEMA_VERSION", default="1.0.0")

# Resilience & Degraded Mode
SEARCH_DEGRADED_FALLBACK_ENABLED = config("SEARCH_DEGRADED_FALLBACK_ENABLED", default=True, cast=bool)
SEARCH_RATE_LIMIT_QUERIES_PER_MIN = 60
SEARCH_RATE_LIMIT_SUGGESTIONS_PER_MIN = 120

# Index Names / UIDs
INDEX_PATIENTS = "patients"
INDEX_CLINICAL_RECORDS = "clinical_records"
INDEX_PREDICTIONS = "predictions"
INDEX_TRIAGE_RECORDS = "triage_records"
INDEX_CLINICAL_TASKS = "clinical_tasks"
INDEX_ESCALATIONS = "escalations"
INDEX_MODELS = "models"
INDEX_DATA_QUALITY = "data_quality"
INDEX_AI_EVALUATIONS = "ai_evaluations"
INDEX_WHITEBOARDS = "whiteboards"
INDEX_SYSTEM_EVENTS = "system_events"
INDEX_KNOWLEDGE_SOURCES = "knowledge_sources"

ALL_INDEXES = [
    INDEX_PATIENTS,
    INDEX_CLINICAL_RECORDS,
    INDEX_PREDICTIONS,
    INDEX_TRIAGE_RECORDS,
    INDEX_CLINICAL_TASKS,
    INDEX_ESCALATIONS,
    INDEX_MODELS,
    INDEX_DATA_QUALITY,
    INDEX_AI_EVALUATIONS,
    INDEX_WHITEBOARDS,
    INDEX_SYSTEM_EVENTS,
    INDEX_KNOWLEDGE_SOURCES,
]

# Data Classifications
CLASSIFICATION_PUBLIC = "PUBLIC"
CLASSIFICATION_INTERNAL = "INTERNAL"
CLASSIFICATION_SENSITIVE = "SENSITIVE"
CLASSIFICATION_PHI = "PHI"
CLASSIFICATION_RESTRICTED = "RESTRICTED"

INDEX_CLASSIFICATIONS = {
    INDEX_PATIENTS: CLASSIFICATION_PHI,
    INDEX_CLINICAL_RECORDS: CLASSIFICATION_PHI,
    INDEX_PREDICTIONS: CLASSIFICATION_SENSITIVE,
    INDEX_TRIAGE_RECORDS: CLASSIFICATION_SENSITIVE,
    INDEX_CLINICAL_TASKS: CLASSIFICATION_INTERNAL,
    INDEX_ESCALATIONS: CLASSIFICATION_SENSITIVE,
    INDEX_MODELS: CLASSIFICATION_INTERNAL,
    INDEX_DATA_QUALITY: CLASSIFICATION_INTERNAL,
    INDEX_AI_EVALUATIONS: CLASSIFICATION_INTERNAL,
    INDEX_WHITEBOARDS: CLASSIFICATION_INTERNAL,
    INDEX_SYSTEM_EVENTS: CLASSIFICATION_RESTRICTED,
    INDEX_KNOWLEDGE_SOURCES: CLASSIFICATION_PUBLIC,
}
